### ISSUE TITLE
[NEW FEATURE] 关于投屏只能720p的问题

### ISSUE THREAD

**Issue by DandyChan** [xfangfang/Macast#100]
由于B站限制了投屏的清晰度（除了B站电视端），最高只能720p，不知道是否有解决办法

**Comment by xfangfang** [comment]
关于这个问题的相关讨论：https://github.com/xfangfang/Macast/issues/30#issuecomment-939444038

**Comment by Passerby1011** [comment]
不只是b站，好多视频网站都是只有720p，只能投给对应客户端

**Comment by xfangfang** [comment]
正在处理这个问题，目前的解决办法是，将协议部分提出来当作插件使用，开放给大家去适配更多的客户端协议。目前已经初步完成了b站的协议适配，还在整理代码中

**Comment by xfangfang** [comment]
最新的测试版支持了“协议插件“，允许基于这个特性开发适配不同协议。尝试了一下这个问题讨论的协议，目前大体功能正常，需要测试的朋友可以进群：983730955

**Comment by xfangfang** [comment]
@DandyChan 如果没人理我我就关闭这个issue了？
