### ISSUE TITLE
[NEW FEATURE] Support Youku,Tencent,IQY

### ISSUE THREAD

**Issue by BayMRX** [xfangfang/Macast#101]
## New feature
希望可以支持优爱腾的高清投屏播放，支持！！

## Additional context
(Add any other context or screenshots about the feature request here.)

**Comment by xfangfang** [comment]
不要在这里发插件相关的issue，Macast这个仓库只支持 标准DLNA于MPV播放器，其他内容请发送到：https://github.com/xfangfang/Macast-plugins

顺便一提，不要指望我做，大家都是程序猿，有需求自己实现，欢迎提交代码
