### ISSUE TITLE
[NEW FEATURE] Scoop install Manifests

### ISSUE THREAD

**Issue by happytommyl** [xfangfang/Macast#102]
## New feature
Hope you can add `scoop` support for the Windows platform.

## Additional context

Here's my proposal for the install Manifests. I tested it on my PC. If you may test it again without any issue, then I would propose it to the scoop bucket. Thanks.

```json
{
    "version": "0.7",
    "description": "Macast GUI",
    "homepage": "https://github.com/xfangfang/Macast",
    "license": "GNU General Public License v3.0",
    "architecture": {
        "64bit": {
            "url": "https://github.com/xfangfang/Macast/releases/download/v0.7/Macast-Windows-v0.7.exe"
        }
    },
    "bin": [["Macast-Windows-v0.7.exe", "macast" ]],
    "shortcuts": [
        [
            "Macast-Windows-v0.7.exe",
            "macast"
        ]
    ],
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/xfangfang/Macast/releases/download/v$version/Macast-Windows-v$version.exe"
            }
        }
    },
    "checkver": "github"
}
```

**Comment by xfangfang** [comment]
Thank you very much for your contribution!
I will update the wiki later after it can be downloaded through scoop.

Tested in a new environment, everything looks good to me.

**Comment by happytommyl** [comment]
Ok, I'll make a PR to the scoop bucket

**Comment by happytommyl** [comment]
The manifest has been added to the `extras` bucket, can now be installed with
```
scoop bucket add extras
scoop install macast
```

on Windows platform

**Comment by xfangfang** [comment]
> The manifest has been added to the `extras` bucket, can now be installed with
> 
> ```
> scoop bucket add extras
> scoop install macast
> ```
> 
> on Windows platform

Great!!!

---

Add to wiki: https://github.com/xfangfang/Macast/wiki/Installation#scoop

**Comment by yaohunzhanyue** [comment]
> > The manifest has been added to the `extras` bucket, can now be installed with
> > ```
> > scoop bucket add extras
> > scoop install macast
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > on Windows platform
> 
> Great!!!
> 
> Add to wiki: https://github.com/xfangfang/Macast/wiki/Installation#scoop

Could you add debug version in scoop?

**Comment by happytommyl** [comment]
I didn't use the debug version. I may look into it later.

**Comment by happytommyl** [comment]
> > > The manifest has been added to the `extras` bucket, can now be installed with
> > > ```
> > > scoop bucket add extras
> > > scoop install macast
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > on Windows platform
> > 
> > 
> > Great!!!
> > Add to wiki: https://github.com/xfangfang/Macast/wiki/Installation#scoop
> 
> Could you add debug version in scoop?

debug version can now be installed with:
`scoop install macast-debug`
