### ISSUE TITLE
[BUG] Not checking existing instance

### ISSUE THREAD

**Issue by happytommyl** [xfangfang/Macast#103]
## Versions

- System: Windows

## Windows

The program does not check if the program is already running, which would result in multiple running instances. Each instance would run on a different port and will show up as a different device on the mobile side. Don't know if this is intended?

**Comment by xfangfang** [comment]
At first, I developed `Macast` on MacOS. MacOS will automatically prohibit the second instance from being opened, so I haven't encountered this problem.

Unfortunately, it is found that applications may be opened more than one time on the windows platform, but if the application encounters a port conflict when it is opened, it will automatically switch to the available port and switch to a random name.

Seems It won't cause too much problem, so I didn't try to fix it. If you are interested in this, you can try to fix it and add a new setting option to allow the software to open more (this option can be turned off by default) to avoid affecting people who need this function.

**Comment by xfangfang** [comment]
Thank you very much ~
The code has been merged to dev branch.

https://github.com/xfangfang/Macast/pull/122
