### ISSUE TITLE
doesn't show any menu/window/gui on monterey

### ISSUE THREAD

**Issue by mailinglists35** [xfangfang/Macast#115]
it only makes some intense disk I/o and shows in activity monitor, and firewall asks it it allows the app to open a listening port and allow outgoing connection to GitHub. but that's all.

**Comment by xfangfang** [comment]
After macast runs, it will appear in the menu bar. The menu and running screenshots are shown in the link:
https://github.com/xfangfang/Macast/wiki/FAQ#i-dont-know-how-to-use

You need to find a DLNA enabled mobile client to use with Macast. (It can be nplayer on iOS, and BubbleUPnP on Android)

Then you can quickly display the video, pictures and music in the mobile phone on the computer. This is what DLNA media renderer does.

Many TV have this feature, Macast is designed for those who want to have this function on the computer.

**Comment by mailinglists35** [comment]
alright, found the cause: the icon is not visible when there are already too many icons and menus on the menu bar.

**Comment by mailinglists35** [comment]
I don't see it on iPhone neither as an airplay target nor as a chromecast tv.

how exactly do you send streams to it?

the mentioned nplayer app does not see my dlna server, even though vlc does.

**Comment by xfangfang** [comment]
> I don't see it on phone neither as an airplay target nor as a chromecast tv. how exactly do you send streams to it? the mentioned nplayer app does not see my dlna server, even though vlc does.

Macast is a **DLNA Media Renderer**.

DLNA Media Renderer != DLNA server  
DLNA Media Renderer != Airplay  
DLNA Media Renderer != Chromecast

![IMG_F32983D1B9A2-1](https://user-images.githubusercontent.com/16631584/151798457-1c59a480-0c11-4b01-a14b-a9a13d39639e.jpeg)

**Comment by mailinglists35** [comment]
okay I finally understand, so this app should appear as a TV to my phone when I tap the chromecast button in a player. But it doesn't, so I should file a different issue.

the initial report remains valid though, and I think there is nothing you can do except add a UI main window. relying only on the menu bar icon is not reliable when the menu is full.

**Comment by xfangfang** [comment]
When Macast cannot be found on the phone, please see the FAQ: https://github.com/xfangfang/Macast/wiki/FAQ#unable-to-find-macast-from-your-dlna-client

> the initial report remains valid though, and I think there is nothing you can do except add a UI main window. relying only on the menu bar icon is not reliable when the menu is full.

Many applications on MacOS have this problem, which should be the problem of MacOS. Adding a UI is a good idea, but considering that it takes a lot of time to develop it for normal use on multiple platforms, I don't have enough time at present, hope it will be improved in the future
