### ISSUE TITLE
[Question] what exactly does this app do?

### ISSUE THREAD

**Issue by mailinglists35** [xfangfang/Macast#116]
## Versions

- System version: (eg:11.4)
- Processor architecture: (eg:X86)
- APP version: (eg: v0.2)

## Problem

(your problem description here)
can you show a video tutorial? I don't understand what this does? is it a DLNA server(receiver)? a client? what? I read the FAQs but it doesn't answer this simple question.

**Comment by xfangfang** [comment]
Sorry for the confusion. Macast is a **DLNA media renderer**

There is a description at the beginning of the wiki: https://github.com/xfangfang/Macast/wiki/GetStarted#what-is-macast
