### ISSUE TITLE
[NEW FEATURE] [NVA ] 限制弹幕范围 

### ISSUE THREAD

**Issue by xgdgsc** [xfangfang/Macast#117]
## New feature
限制弹幕范围在屏幕上方，像b站网页版选项一样

另外还想知道弹幕透明度能否设置，是否mpv目前还不支持这些功能（我没找到）

**Comment by xfangfang** [comment]
Please do not send `Macast Plugin` related content to this repo.

[Macast-plugins](https://github.com/xfangfang/Macast-plugins)

---

弹幕透明度是在插件代码中设置的，目前只写了一个默认的透明度。

相关代码：
https://github.com/xfangfang/Macast-plugins/blob/fdbfcb51a96beda7b13bd08bdc392f00923cac0d/nirvana/nirvana.py#L740-L741


弹幕生成的其他代码在：
https://github.com/xfangfang/Macast-plugins/blob/fdbfcb51a96beda7b13bd08bdc392f00923cac0d/nirvana/nirvana.py#L628


欢迎给这个插件添加可供配置的选项：
配置文件读写示例代码：
```
class SettingProperty(Enum):
    SETTING_1 = 1
    SETTING_2 = 0
    SETTING_3 = 1

default = 66
Setting.get(SettingProperty.SETTING_1.value, default)

value = 33
Setting.set(SettingProperty.SETTING_1.value, value)

```

**Comment by xfangfang** [comment]
因为没有后续更新，所以先关闭这个issue
