### ISSUE TITLE
mac os 系统0.7版本，不选择player ontop，默认在第二个桌面里面会变成ontop，而且无法关闭

### ISSUE THREAD

**Issue by mycs888-sudo** [xfangfang/Macast#119]
## Versions

- System version: bigsur 11.2.3
- Processor architecture: m1
- APP version: 0.7

## Problem

mac os 系统，0.7版本，不选择player ontop投屏，默认在第二个桌面里面会变成ontop播放，而且无法关闭，回退回0.65版本就正常，不知道mpv哪个地方要设置下？

**Comment by xfangfang** [comment]
感谢反馈，目前macos上添加了mpv启动参数 on-all-workspaces，这个参数本意是搭配ontop模仿小窗播放的，后来把ontop选项设置放在菜单中之后忘记把它(on-all-workspaces)也一起配置了，所以造成了mpv会显示在所有桌面上（但不是ontop）

在Github-Actions中可找到修复这个问题的构建：https://github.com/xfangfang/Macast/actions/runs/1827793299
