### ISSUE TITLE
[Question] 无法连接到插件商店是什么问题

### ISSUE THREAD

**Issue by tshouzy** [xfangfang/Macast#121]
最新版本的，点击高级设置之后就显示如下图所示的无法连接到插件商店，这是出了什么问题吗，求解答，谢谢。
电脑是win11的。
![uTools_1644737185882](https://user-images.githubusercontent.com/77475860/153743773-86badb2c-de25-4e70-a1a6-7e94cc0510d7.png)

**Comment by xfangfang** [comment]
Duplicate issue? : https://github.com/xfangfang/Macast/issues/106

**Comment by xfangfang** [comment]
因为没有后续反馈，先关闭了
