### ISSUE TITLE
播放器设置里面，弄一个倍速功能，最好能设置默认速度，习惯了2倍看视频[NEW FEATURE] Type your title here

### ISSUE THREAD

**Issue by AirMax121** [xfangfang/Macast#124]
## New feature
(type your idea here)
播放器设置里面，弄一个倍速功能，最好能设置默认速度，习惯了2倍看视频
## Additional context
(Add any other context or screenshots about the feature request here.)

**Comment by xfangfang** [comment]
推荐使用播放器支持的快捷键调节倍速，或者配置自己需要的快捷键：
https://github.com/xfangfang/Macast/wiki/常见问题#播放器快捷键是什么

如果需要配置默认倍速，请看：
https://github.com/xfangfang/Macast/wiki/常见问题#定制mpv内置播放器功能

**Comment by xfangfang** [comment]
@AirMax121 If there are no other questions, I'll close this issue?
