### ISSUE TITLE
Erro with BiliBili-NirvanaControl

### ISSUE THREAD

**Issue by evlic** [xfangfang/Macast#126]
## Versions

- OS: macOS Catalina 10.15.7 19H1715 x86_64 
- APP version: (v0.7)

> Plugin version:
![](https://gitee.com/evlic/gallery/raw/master/pic/2022-03/kAzAwD｜YBRZ88.png)

## Bug recurrence

with plugin MPV & NVA using bilibili “必连”
![](https://gitee.com/evlic/gallery/raw/master/pic/2022-03/KuEA7i｜B2QV83.jpg)

## Log
192.168.77.181 - - [03/Mar/2022:09:14:22] "POST /NirvanaControl/action HTTP/1.1" 200 276 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.77.181 - - [03/Mar/2022:09:14:22] "POST /NirvanaControl/action HTTP/1.1" 200 276 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.77.181 - - [03/Mar/2022:09:14:22] "POST /AVTransport/action HTTP/1.1" 200 237 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.77.181 - - [03/Mar/2022:09:14:22] "POST /AVTransport/action HTTP/1.1" 200 224 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.77.181 - - [03/Mar/2022:09:14:23] "POST /NirvanaControl/action HTTP/1.1" 200 283 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.77.181 - - [03/Mar/2022:09:14:24] "POST /NirvanaControl/action HTTP/1.1" 200 276 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.77.181 - - [03/Mar/2022:09:14:24] "POST /NirvanaControl/action HTTP/1.1" 200 276 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.77.181 - - [03/Mar/2022:09:14:25] "POST /NirvanaControl/action HTTP/1.1" 200 276 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.77.181 - - [03/Mar/2022:09:14:25] "POST /NirvanaControl/action HTTP/1.1" 200 276 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.77.181 - - [03/Mar/2022:09:14:26] "POST /NirvanaControl/action HTTP/1.1" 200 276 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.77.181 - - [03/Mar/2022:09:14:26] "POST /NirvanaControl/action HTTP/1.1" 200 276 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.77.181 - - [03/Mar/2022:09:14:27] "POST /NirvanaControl/action HTTP/1.1" 200 276 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.77.181 - - [03/Mar/2022:09:14:27] "POST /NirvanaControl/action HTTP/1.1" 200 276 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
127.0.0.1 - - [03/Mar/2022:09:14:28] "GET /?page=3 HTTP/1.1" 200 26758 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36"
192.168.77.181 - - [03/Mar/2022:09:14:28] "POST /NirvanaControl/action HTTP/1.1" 200 276 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.77.181 - - [03/Mar/2022:09:14:28] "POST /NirvanaControl/action HTTP/1.1" 200 276 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
127.0.0.1 - - [03/Mar/2022:09:14:29] "GET /api?query=log HTTP/1.1" 200 41066 "http://127.0.0.1:63992/?page=3" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36"
127.0.0.1 - - [03/Mar/2022:09:14:29] "GET /api?query=plugin-info HTTP/1.1" 200 1956 "http://127.0.0.1:63992/?page=3" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36"

**Comment by xfangfang** [comment]
1. Please use the method specified in the issue template[bug report] to obtain the application log.
2. Maybe you should describe something about how to trigger this bug.

**Comment by evlic** [comment]
This problem has been solved
