### ISSUE TITLE
已退出进程，代码128

### ISSUE THREAD

**Issue by congcheng-qu** [xfangfang/Macast#129]
## Versions

- System version: win11 dev 22h2 22567.200
- Processor architecture: windows  X86架构
- APP version: V0.7

## Problem
手机投屏显示三个CMD窗口 ，一已退出，代码128
![image](https://user-images.githubusercontent.com/72257490/157362839-291235db-05de-40e2-9ee8-7d0b029aa3e0.png)

**Comment by xfangfang** [comment]
可不可以详细描述一下操作呢？正常来说图中弹出的cmd窗口是与程序无关的。
要确认三件事：
1 是每次投屏都会弹出三个cmd吗？
2 下载之后有没有做过什么额外操作，比如安装插件之类的
3 为什么windows x86能运行这个软件，目前的release还不支持x86

可以再尽可能详细的描述一下您做过什么，现在我看到这个反馈的感觉就是：投屏之后莫名其妙爆发了核战争。

但是我完全不知道为什么核战争会和投屏有关系

**Comment by congcheng-qu** [comment]
对每次投屏都会出现，用的使Potplayer插件，有时候potplay不会启动，只弹出三个cmd窗口，对了我电脑连的手机热点，还有使用的是X64架构的处理器，64位的win11,之前打错了，抱歉

**Comment by xfangfang** [comment]
@congcheng-qu 刚刚小更新了一下插件，可以重新下载试试：https://github.com/xfangfang/Macast-plugins/blob/main/potplayer/potplayer.py

**Comment by congcheng-qu** [comment]
好的，谢谢

**Comment by congcheng-qu** [comment]
好了，问题已解决，麻烦了

**Comment by xfangfang** [comment]
感谢详细又及时的反馈，有问题随时沟通，先关闭这个issue了
