### ISSUE TITLE
连接界面排版(a new DLNA control page design)

### ISSUE THREAD

**Issue by z-c-w** [xfangfang/Macast#13]
## New feature
(对手机端的连接界面进行改版「更像一个遥控器」)

## Additional context
(这是我的一个想法，连接设备后，会有提示。)
![image](https://user-images.githubusercontent.com/35092761/130103814-adcbc934-edfd-4bb0-9a1e-92d4bc3944ae.png)

**Comment by xfangfang** [comment]
非常棒的界面设计，但是很遗憾目前的手机端控制页面并不受Macast控制，而是投屏软件本身的设计，各家不仅界面实现的不一样，甚至投屏协议实现的也都不太一样，是DLNA投屏的遗憾了。

---

Great design, but unfortunately, the current DLNA control page is not controlled by Macast, but the DLNA control application itself.

**Comment by xfangfang** [comment]
Thank you very much for your design. In order to avoid disturbing others to view the issue list, close this issue.
