### ISSUE TITLE
How do I get youtube music output? Bubble uPnp Linux, pip install from git, pipewire audio. No audio output from from macast.

### ISSUE THREAD

**Issue by timrichardson** [xfangfang/Macast#137]
## Versions
followed instructions for pip install from git
I installed as my user, not as sudo. I ran into the problem of this missing config directory, which was easily fixed.
I have mpv installed. 

## Problem
It looks like the dlna renderer is working: I can see it as an output in BubbleUPnP.
Then in BubblePnP I turn on audio cast and play a track from youtube music.
Because I ran macast from a terminal, I can see lots of output from the cherrypy server and it seems very active, lots of messages scroll and it looks healthy. 

However, I get no audio output. I am using xubuntu 22.04 with pipewire. When I run pulse audio volume control it shows me all audio streams and applications playing, but there is nothing from macast. It's like it doesn't exist.

**Comment by xfangfang** [comment]
I haven't tested with xubuntu. It's hard to say which part caused the problem. You can do the followings:
1. Check whether MPV is running when casting audio.( It should be running or something wrong just happened.)
2. Try casting video with BubbleUPnP(This step is to confirm whether the casting is successful)
3. Most importantly, please submit the issue according to the issue template. When there is a problem, reading the log is the easiest way to understand the actual situation)

**Comment by timrichardson** [comment]
thanks, I needed to know if it was supposed to work. I will close this, and gather information to file a bug. I can see that mpv is started. I will test with video and then if that works investigate more about the audio.

**Comment by timrichardson** [comment]
Update: it works, after I changed Bubble uPnP settings like so:
AudioCast settings: set Audio format to WAV (default is Auto).
Possibly some other settings work, but the default Bubble uPnP settings do not work.

**Comment by xfangfang** [comment]
Maybe it’s the mpv that you are using does   not support the default audio format of youtube.
Thank you very much for your reply. I'll try it when I'm free.
