### ISSUE TITLE
转发哪个端口能跨网段

### ISSUE THREAD

**Issue by WeihuaGu** [xfangfang/Macast#139]
macast装在debian盒子上，盒子的网址是192.168.9.1。然后盒子上插了无线网卡做ap,网段是192.168.5.0/24.
现在我想让手机搜到，应该在手机上转发哪个端口？
```sh
socat tcp-listen:XXX tcp:192.168.9.1:XXX
```

**Comment by xfangfang** [comment]
DLNA协议过程中手机也可能会打开随机端口用于通讯，常见于音乐软件。

Macast使用的是原生DLNA协议，手机搜索不到，说明目前的服务发现不可用，服务发现对应SSDP协议，使用了组播通讯，组播地址为：239.255.255.250:1900

另外使用到了一个tcp端口用于DLNA协议的其余部分，具体的端口号见应用菜单栏，亦可于配置文件中设置。

（我不了解SSDP组播转发之后还能不能正常工作，可能和手机端的实现也相关，不过可以尝试尝试，期待你的结果）

**Comment by WeihuaGu** [comment]
@xfangfang 好的，感谢，我试试。。。

**Comment by WeihuaGu** [comment]
没成功。盒子ip:192.168.9.2 无线网卡接口wlx00e04c17225b
我先是在盒子上，也就是装有macast的机器上做了转发
```sh
sudo iptables -t nat -A POSTROUTING -p udp -s 192.168.9.2 -d 239.255.255.250 -o wlx00e04c17225b -j MASQUERADE
```
然后我在手机上监听1068,就是菜单设置里的端口
```sh
socat tcp-listen:1068 tcp:192.168.9.2:1068
```
还是搜索不到。

我能大概理解，macast类似在循环做这样的事：
```sh
echo '我这有一个upnp的服务' | socat - UDP4-DATAGRAM:239.255.255.250:1900,broadcast,range=192.168.9.0/24
```
我不知道怎么吧这个组播转发到192.168.5.0/24的子网。组播和广播不同，它不是基于地理位置的，而是逻辑组。。。

**Comment by xfangfang** [comment]
我也不是十分了解这个问题了。

找到了一个貌似可供参考的论坛讨论：https://www.hostloc.net/thread-31640-1-1.html

**Comment by WeihuaGu** [comment]
感谢。
