### ISSUE TITLE
[Question] go2tv couldn't find the DMR of Macast

### ISSUE THREAD

**Issue by allanpk716** [xfangfang/Macast#141]
## Versions

- System version: Windows 10
- Processor architecture: X64
- APP version: v0.7

## Problem

With this program on, I can use Bilibili to cast the screen over the LAN. But using this tool [go2tv](github.com/alexballas/go2tv), I couldn't find the DMR of Macast, then on the same computer, I installed 5KPlayer and tested Bilibili and [go2tv](github.com/alexballas/go2tv). Both of them can cast screen. The [go2tv](github.com/alexballas/go2tv) can search the DMR provided by 5KPlayer, but it can't search the DMR of Macast.

开启本程序，局域网内可以使用 Bilibili 投屏过来。但是使用这个工具 [go2tv](github.com/alexballas/go2tv) 则无法找到 Macast 的 DMR。然后相同的电脑上，我装了 5KPlayer，也测试了 Bilibili 和 [go2tv](github.com/alexballas/go2tv) 都是可以投屏的。[go2tv](github.com/alexballas/go2tv) 可以搜索到 5KPlayer 提供的 DMR，但是无法搜索到 Macast 的 DMR。

**Comment by xfangfang** [comment]
<img width="880" alt="image" src="https://user-images.githubusercontent.com/16631584/175898960-9d878cd7-26c3-498e-b129-6f6f0c39a7e2.png">

macOS上，同时运行go2tv和Macast，貌似是正常的 。

Windows用户如何查看Log：
关闭Macast，打开CMD，并从Github下载Debug版的Macast，将Macast拖入CMD，回车执行。然后使用go2tv搜索设备，等待1分钟左右，关闭Macast，并提交此时终端中出现的log，或许看log能有一些帮助。

**Comment by allanpk716** [comment]
这个是看到的日志，其中`192.168.31.224`这个是我本机电脑的地址。以及，我有多块网卡。

### 日志
Macast Loading Language: zh_CN
{'Additional_Interfaces': [], 'ApplicationPort': 65149, 'Blocked_Interfaces': [], 'CheckUpdate': 1, 'DLNA_FriendlyName': 'Macast(LifeIsFloatBook)', 'Macast_Protocol': 'DLNA Protocol', 'Macast_Renderer': 'MPV Renderer', 'MenubarIcon': 0, 'PlayerDefaultVolume': 100, 'PlayerHW': 1, 'PlayerOntop': 1, 'PlayerPosition': 2, 'PlayerSize': 1, 'StartAtLogin': 0, 'USN': 'f117f774-9543-47c8-a078-f6c63113ccec'}
using plugin: MPV Renderer
using plugin: DLNA Protocol
(2, 'RegDeleteValue', '系统找不到指定的文件。')
INFO:cherrypy.error:[27/Jun/2022:17:25:07] ENGINE Set handler for console events.
ERROR:SSDPServer:add membership 192.168.31.224
INFO:MPVRenderer:starting mpv and mpv ipc
ERROR:SSDPServer:add membership 192.168.137.1
ERROR:SSDPServer:[WinError 10049] 在其上下文中，该请求的地址无效。
INFO:MPVRenderer:mpv starting
INFO:cherrypy.error:[27/Jun/2022:17:25:07] ENGINE Started monitor thread 'Autoreloader'.
INFO:cherrypy.error:[27/Jun/2022:17:25:07] ENGINE Started monitor thread 'SSDP_NOTIFY_THREAD'.
INFO:cherrypy.error:[27/Jun/2022:17:25:07] ENGINE Bus STARTED
INFO:server:Server current run on port: 65149
INFO:main:tag_name: v0.7
ERROR:MPVRenderer:mpv ipc socket start connect
INFO:MPVRenderer:{'event': 'property-change', 'id': 1, 'name': 'volume', 'data': 100.0}
INFO:MPVRenderer:{'event': 'property-change', 'id': 3, 'name': 'pause', 'data': False}
ERROR:SSDPServer:drop membership 192.168.31.224
ERROR:SSDPServer:drop membership 192.168.137.1
INFO:main:ssdp_update_ip
ERROR:SSDPServer:add membership 192.168.31.224
ERROR:SSDPServer:add membership 192.168.137.1
ERROR:SSDPServer:[WinError 10049] 在其上下文中，该请求的地址无效。
ERROR:SSDPServer:drop membership 192.168.31.224

**Comment by xfangfang** [comment]
这个log显示并没有被go2tv搜索到（而不是搜索到了，但因为协议不匹配而没有显示），一般出现这个问题都是由防火墙或其他网络问题导致的。

刚刚我在本地测试：macOS运行go2tv，Windows运行Macast也是正常工作的。

所以我想问题可能还是出在您那边的某些配置上，不知道您使用什么设备运行的go2tv呢？以及这个设备的内网IP是多少？可以尝试使用这个设备访问：192.168.31.224:65149 看看有没有响应

**Comment by allanpk716** [comment]
1. 尝试访问 192.168.31.224:65149  这个是可以的，因为高级设置是 Web 页面
2. 系统信息见下图
3. 防火墙我关闭了也不行

## 系统信息
![image](https://user-images.githubusercontent.com/1176000/175914590-b65b257f-69bd-4adc-83bc-c483e387984e.png)

**Comment by xfangfang** [comment]
您是在同一台电脑上运行的go2tv与Macast吗？

因为我确实没办法在本地复现这个问题，所以暂时还是没有什么解决办法，只能靠您那边自己找出来原因了。

刚刚使用最新的代码构建了一下，也可以使用这个来试一试：
https://github.com/xfangfang/Macast/actions/runs/2568438218

（构建好之后在网页下部就可以下载了）

**Comment by allanpk716** [comment]
> 您是在同一台电脑上运行的go2tv与Macast吗？
> 
是的，回家我再试试分开两台会如何。也会试试你新构建的再反馈。

**Comment by allanpk716** [comment]
使用刚才构建的 debug 版本得到的运行日志

[log.txt](https://github.com/xfangfang/Macast/files/8991076/log.txt)

**Comment by xfangfang** [comment]
> 使用刚才构建的 debug 版本得到的运行日志
> 
> [log.txt](https://github.com/xfangfang/Macast/files/8991076/log.txt)

这个log看起来就是正常启动的log

**Comment by allanpk716** [comment]
回家使用了两台虚拟机：
1. Win11，Macast
2. Windows 2019 Server，go2tv
还是无法搜索到 DMR，两台机器都关闭了防火墙。

[log.txt](https://github.com/xfangfang/Macast/files/8996607/log.txt)

**Comment by xfangfang** [comment]
@allanpk716 我找到问题所在了，原因是Macast为了减少无用的流量，在组播时设置了 IP_MULTICAST_LOOP 为 0，在windows上，这会导致Macast不接受来自本机的数据。
我不清楚为什么虚拟机会出现同样的问题，大概和虚拟机的网络设定有关。

这个问题找两台真实的电脑试验，go2tv是没问题的。

**Comment by allanpk716** [comment]
> @allanpk716 我找到问题所在了，原因是Macast为了减少无用的流量，在组播时设置了 IP_MULTICAST_LOOP 为 0，在windows上，这会导致Macast不接受来自本机的数据。 我不清楚为什么虚拟机会出现同样的问题，大概和虚拟机的网络设定有关。
> 
> 这个问题找两台真实的电脑试验，go2tv是没问题的。

好的，我找两台真机试试

**Comment by xfangfang** [comment]
因为没有后续更新，所以先关闭这个issue
