### ISSUE TITLE
多网卡监听地址问题

### ISSUE THREAD

**Issue by WeihuaGu** [xfangfang/Macast#142]
## Versions

- System version: (5.15.48-rockchip64  debian)
- Processor architecture: (aarch64 )
- APP version: (macast    0.65.post1)

## Problem

我看issue，最新的是支持多网卡的。但是它还是只监了一个网卡。
```sh
enx00e04c36022f: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.6.1  netmask 255.255.255.0  broadcast 192.168.6.255
       
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.9.2  netmask 255.255.255.0  broadcast 192.168.9.255
   
wlx00e04c17225b: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 2312
        inet 192.168.5.1  netmask 255.255.255.0  broadcast 192.168.5.255
       
```
我想让应用监听网卡wlx00e04c17225b的192.168.5.1. 但应用监听的是eth0的192.168.9.2

访问192.168.9.2:1068是正常的，192.168.5.1:1068没有页面.

**Comment by xfangfang** [comment]
修改配置文件，然后重启应用应该就可以了。

相关配置项：Additional_Interfaces，将网卡名作为字符串填进去

---

视频演示：https://www.bilibili.com/video/BV1Z64y1b7FR?t=95.0

**Comment by WeihuaGu** [comment]
好了。：）
plus ,有配置项的说明文档嘛

**Comment by xfangfang** [comment]
可以查看一下项目的wiki：https://github.com/xfangfang/Macast/wiki/常见问题#macast配置文件目录

配置内容不多，配置项的名称基本都是自解释的，也欢迎为这个项目的wiki贡献时间～

**Comment by WeihuaGu** [comment]
好的 ^_^
