### ISSUE TITLE
请问一下可以把mac电脑的视频投到电视上吗

### ISSUE THREAD

**Issue by duolabmeng6** [xfangfang/Macast#144]
我试了一下...这是把手机的视频投到mac电脑上
那么 可以在mac上的视频投到电视上吗

**Comment by xfangfang** [comment]
https://github.com/alexballas/go2tv

**Comment by duolabmeng6** [comment]
> https://github.com/alexballas/go2tv

感谢大佬~

**Comment by duolabmeng6** [comment]
<img width="768" alt="image" src="https://user-images.githubusercontent.com/59047063/181578865-3d73e441-64ac-4074-afb3-4ab610d3425f.png">
测试了一下投屏非常迅速 很棒~~~~
