### ISSUE TITLE
手机无线投屏可以投吗？

### ISSUE THREAD

**Issue by zwtocn** [xfangfang/Macast#145]
不是投视频，手机镜像或者华为的无线投屏可以切换pc模式

**Comment by xfangfang** [comment]
原则上应用层协议都可以通过Macast的插件适配来支持。

华为的无线同屏可能不仅仅工作在应用层，所以应该是不行的。
手机屏幕镜像根据协议的不同有可能有机会支持，但是现实是没有人写这样的适配插件。

**Comment by zwtocn** [comment]
好的  挺遗憾

**Comment by zwtocn** [comment]
> 原则上应用层协议都可以通过Macast的插件适配来支持。
> 
> 华为的无线同屏可能不仅仅工作在应用层，所以应该是不行的。 手机屏幕镜像根据协议的不同有可能有机会支持，但是现实是没有人写这样的适配插件。

好的 挺遗憾

**Comment by zwtocn** [comment]
> > 原则上应用层协议都可以通过Macast的插件适配来支持。
> > 华为的无线同屏可能不仅仅工作在应用层，所以应该是不行的。手机屏幕镜像根据协议的不同有可能有机会支持，但现实是没有人写这样的适配插件。
> 
> 好的挺遗憾
