### ISSUE TITLE
[NEW FEATURE] 如何编译 ARM64  Linux 版本?

### ISSUE THREAD

**Issue by work4blue** [xfangfang/Macast#147]
## New feature
relase 里只有linux arm7的版本,请问一下我用ARM64 的编译aarch64-linux-gnu-gcc 如何编译?

**Comment by xfangfang** [comment]
可以参考这里构建

https://github.com/xfangfang/Macast/blob/ee58f4ec497704536461749c3afa659caccc34e0/.github/workflows/build-macast.yaml#L266-L331

下面是构建好的，可以顺便测试一下能不能正常使用。

https://github.com/xfangfang/Macast/actions/runs/2605059596


也可以直接通过pip来安装，wiki中有写，这种方式运行可能会遇到一些兼容的问题

**Comment by work4blue** [comment]
我看到一下脚本,只能把代码拷到开发板打包了

**Comment by work4blue** [comment]
不是amd64 也是不是  armv7 armv8 ,列表里没有,是ARM64 的,现在新出的开发板rockship 都是这个cpu

**Comment by xfangfang** [comment]
> 不是amd64 也是不是 armv7 armv8 ,列表里没有,是ARM64 的,现在新出的开发板rockship 都是这个cpu

我不是很了解不同架构之间的区别，但是您有尝试过那个列表中的armv8吗？我感觉或许可以使用的

**Comment by xfangfang** [comment]
因为没有后续更新，所以先关闭这个问题
