### ISSUE TITLE
[BUG] 出现视频链接错误，部分应用投屏失败

### ISSUE THREAD

**Issue by lonevle** [xfangfang/Macast#148]
## Versions

- System: (eg:windows10)
- APP version: (eg: v0.7)

## Bug

在使用部分安卓应用投屏时，视频链接的地址出现错误
下面是从程序复制出的视频链接
```
http://127.0.0.1:7000/resource.m3u8?src=aHR0cDovL3hzMnguaG91cGVuZ2xhd3llci5jb20vdm9kL20zdTgvMi8yMDIyLzAyLzI0MTcwMS80NTI2NTEyL2luZGV4My5tM3U4
```
这个并不是真实的视频链接，导致无法投屏

测试将这个链接的127.0.0.1本地IP修改为投屏手机的IP，如192.168.1.87，便可以正常播放

所以实际链接的地址应为投屏设备的ip地址而不是`127.0.0.1`

**Comment by xfangfang** [comment]
这应该是 “部分安卓” 自己的问题，而不是Macast的问题。

**Comment by xfangfang** [comment]
缺乏后续信息，先关闭这个issue
