### ISSUE TITLE
希望添加一个自定义播放器大小选项

### ISSUE THREAD

**Issue by JoelWu** [xfangfang/Macast#15]
## New feature
虽然可以手动调节播放器到合适的窗口大小，但是在投射下一个视频时又会恢复默认选择的窗口大小，希望在这五个选项（小、中、大、自动、全屏）中添加一个自定义大小的选项
## Additional context
(Add any other context or screenshots about the feature request here.)
<img width="220" alt="截屏2021-08-21 17 42 53" src="https://user-images.githubusercontent.com/34499115/130317932-f22a0631-9c59-487b-b8dc-ba2a509544b4.png">

**Comment by xfangfang** [comment]
抱歉，回复的晚了点，您的建议不错，会在下一个版本添加自定义大小的选项的。
反馈崩溃和搜索不到的人太多，为了保证应用稳定性，这几天尽量先解决他们的问题，见谅。
