### ISSUE TITLE
Lastest release can not run on armv7l (raspberrypi)

### ISSUE THREAD

**Issue by listenerri** [xfangfang/Macast#153]
Run macast on terminal, occurs the following errors:
```
Macast Loading Language: zh_CN
{'ApplicationPort': 0, 'CheckUpdate': 1, 'DLNA_FriendlyName': 'Macast(raspberrypi)', 'Macast_Protocol': 'DLNA Protocol', 'Macast_Renderer': 'MPV Renderer', 'MenubarIcon': 0, 'PlayerHW': 1, 'PlayerOntop': 1, 'PlayerPosition': 2, 'PlayerSize': 1, 'StartAtLogin': 0, 'USN': '2830cdc0-7ffe-425f-ac39-3378839add56'}
using plugin: MPV Renderer
using plugin: DLNA Protocol
Traceback (most recent call last):
  File "Macast.py", line 60, in <module>
  File "macast/macast.py", line 510, in gui
  File "macast/macast.py", line 217, in __init__
  File "macast/gui.py", line 122, in __init__
  File "PIL/Image.py", line 2953, in open
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/tmp/_MEIfqK1bB/macast/assets/icon.png'
[16138] Failed to execute script 'Macast' due to unhandled exception!
```

I found that the build script may be causing this problem:

https://github.com/xfangfang/Macast/blob/121add3a8a70edb77e33aeab1ec88aeff27f49fc/.github/workflows/build-macast.yaml#L260

It seems like that the image files not be copied to right place.

Install steps:
- download deb file from [release page](https://github.com/xfangfang/Macast/releases/tag/v0.7)
- run cmd: `sudo apt install Macast-Linux-v0.7-armv7.deb`

**Comment by xfangfang** [comment]
The pictures was copied in the wrong place, because my raspberry pi 3b ran this software too slowly, so there was no actual test.

I hope the build of dev_test branch solves this problem.

https://github.com/xfangfang/Macast/actions/runs/3254749763

**Comment by listenerri** [comment]
@xfangfang 

Macast is working, but it can't be searched, it looks like it's listening on the wrong port number.

![图片](https://user-images.githubusercontent.com/7995379/195975319-d642bd12-e929-486a-8811-f15237ea6bed.png)

**Comment by xfangfang** [comment]
This seems to be a problem with the dev_test branch. Restarting the Macast should solve this problem. This problem only occurs when you first enter the application.

You can also manually modify the application port at: $HOME/.config/Macast

**Comment by listenerri** [comment]
> 

It is working now, thanks.
