### ISSUE TITLE
安卓手机投射到M2 MAC上无任何反应

### ISSUE THREAD

**Issue by jxwuqingyan** [xfangfang/Macast#154]
M2 Mac book pro 上可以正常启动，安卓手机（魅族18）上也能搜到，但是选择了它之后，MAC屏幕上没有任何图像传输

**Comment by jxwuqingyan** [comment]
<img width="529" alt="image" src="https://user-images.githubusercontent.com/18183044/198657809-10cfd290-a05a-47db-b50e-2f3f553dbb1f.png">
![image](https://user-images.githubusercontent.com/18183044/198658306-6321c480-9dd0-4943-b498-4d44e0c76096.png)

**Comment by xfangfang** [comment]
1. 是否只是魅族相册存在问题（这一点，我严重怀疑是魅族自己的问题，之前我用魅族手机来测试时 他偶尔会在投屏后立刻发一个投屏结束的命令，我不是很理解魅族的操作，但是看投屏的相关信息貌似代码有三星写的部分，大概是李楠还在魅族时候和三星合作那会儿搞出来的，这么多年也没更新）
2. 提交问题请尽量按照issue模板来，不看log我也只能猜测

**Comment by jxwuqingyan** [comment]
不好意思，没按模版来，log需要怎么查看？

**Comment by xfangfang** [comment]
> 不好意思，没按模版来，log需要怎么查看？

@jxwuqingyan issue模板中有写

如果确认是只有魅族相册有问题的话，不看log也没关系，魅族的问题需要魅族自己解决

**Comment by jxwuqingyan** [comment]
Macast Loading Language: zh_CN
{'Additional_Interfaces': [], 'ApplicationPort': 51849, 'Blocked_Interfaces': [], 'CheckUpdate': 1, 'DLNA_FriendlyName': 'Macast(wuqingyandeMacBook-Pro.local)', 'Macast_Protocol': 'DLNA Protocol', 'Macast_Renderer': 'MPV Renderer', 'MenubarIcon': 0, 'PlayerDefaultVolume': 100, 'PlayerHW': 1, 'PlayerOntop': 1, 'PlayerPosition': 4, 'PlayerSize': 1, 'StartAtLogin': 0, 'USN': '24d57fc6-7ca5-4dbb-946a-2e78528afc1a'}
using plugin: MPV Renderer
using plugin: DLNA Protocol
GPU list:
GPU:Apple M2
ERROR:SSDPServer:add membership 192.168.31.214
INFO:main:service_start
2022-10-29 13:33:50.706 Macast[30946:12902783] WARNING: the default quit button is disabled. To exit the application gracefully, another button should have a callback of quit_application or call it indirectly.
INFO:cherrypy.error:[29/Oct/2022:13:33:50] ENGINE Serving on http://0.0.0.0:51849
INFO:MPVRenderer:starting mpv and mpv ipc
INFO:MPVRenderer:mpv starting
INFO:cherrypy.error:[29/Oct/2022:13:33:50] ENGINE Started monitor thread 'SSDP_NOTIFY_THREAD'.
INFO:cherrypy.error:[29/Oct/2022:13:33:50] ENGINE Started monitor thread 'Autoreloader'.
INFO:cherrypy.error:[29/Oct/2022:13:33:50] ENGINE Bus STARTED
INFO:server:Server current run on port: 51849
INFO:main:tag_name: v0.7
ERROR:MPVRenderer:mpv ipc socket start connect
INFO:MPVRenderer:{'event': 'property-change', 'id': 1, 'name': 'volume', 'data': 100.0}
INFO:MPVRenderer:{'event': 'property-change', 'id': 3, 'name': 'pause', 'data': False}
INFO:main:ssdp_update_ip
ERROR:SSDPServer:drop membership 192.168.31.214
ERROR:SSDPServer:add membership 192.168.31.214

**Comment by jxwuqingyan** [comment]
好的 明白了 应该是魅族的问题  腾讯视屏这些APP试了没啥问题
