### ISSUE TITLE
[Question] 怎么更改mpv的路径

### ISSUE THREAD

**Issue by WeihuaGu** [xfangfang/Macast#156]
## Problem
Debian 装了两个mpv,一个是自带的不支持硬结，一个是自编译的支持硬解。
我看mpv render 的代码是直接用path='mpv'写死的，配置文件能灵活制定mpv的路径嘛？

**Comment by xfangfang** [comment]
https://github.com/xfangfang/Macast/issues/152#issuecomment-1272256570

**Comment by xfangfang** [comment]
@WeihuaGu 或者我感觉最简单的办法就是删除掉那个不支持硬解的mpv，全局安装你自编译的mpv，反正留着也没用

**Comment by WeihuaGu** [comment]
感谢,试了一下,macast-gui可以,macast-cli失败.
启动macast-gui后,怎么不默认打开浏览器进入更新页?

**Comment by WeihuaGu** [comment]
哦看到了,有不自动检查更新的选项... 再次感谢.
