### ISSUE TITLE
有可能支持MacOS给别的设备投屏吗？

### ISSUE THREAD

**Issue by VeejaLiu** [xfangfang/Macast#164]
有可能支持MacOS给别的设备投屏吗？
比如我现在使用的是Pico

**Comment by xfangfang** [comment]
你可能找的是：https://github.com/alexballas/go2tv

**Comment by VeejaLiu** [comment]
OHHHHHHHHHH~~~~~ ThaNK yOu VERY MucH!!!!!!!
