### ISSUE TITLE
[Question] 手机无法找到设备

### ISSUE THREAD

**Issue by Fengqiv** [xfangfang/Macast#166]
Versions
System: win11
版本 Windows 11 专业版 Insider Preview
版本 22H2
安装日期 ‎2023/‎3/‎9
操作系统版本 25314.1010
体验 Windows Feature Experience Pack 1000.25314.1010.0
Processor architecture: X86
APP version: v0.7

Log
Macast Loading Language: zh_CN
{'Additional_Interfaces': [], 'ApplicationPort': 8428, 'Blocked_Interfaces': [], 'CheckUpdate': 1, 'DLNA_FriendlyName': 'Macast(UUU)', 'Macast_Protocol': 'DLNA Protocol', 'Macast_Renderer': 'MPV Renderer', 'MenubarIcon': 0, 'PlayerHW': 1, 'PlayerOntop': 1, 'PlayerPosition': 2, 'PlayerSize': 1, 'StartAtLogin': 0, 'USN': '3367c504-7779-4494-bc49-7aca990921a4'}
<Load Plugin from nirvana
title : NVA Protocol
protocol : NVAProtocol
platform : darwin,win32,linux
version : 0.31
host_version: 0.7
author : xfangfang
desc : NVA protocol support for Macast. Known as "哔哩必连" v0.31: Fix proxy related problems.
Load plugin NVAProtocol done />

using plugin: MPV Renderer
using plugin: DLNA Protocol
(2, 'RegDeleteValue', '系统找不到指定的文件。')
INFO:main:service_start
ERROR:SSDPServer:add membership 192.168.15.190
ERROR:SSDPServer:add membership 192.168.137.1
ERROR:SSDPServer:[WinError 10049] 在其上下文中，该请求的地址无效。
INFO:cherrypy.error:[22/Mar/2023:20:31:25] ENGINE Set handler for console events.
INFO:MPVRenderer:starting mpv and mpv ipc
INFO:MPVRenderer:mpv starting
INFO:cherrypy.error:[22/Mar/2023:20:31:25] ENGINE Started monitor thread 'Autoreloader'.
INFO:cherrypy.error:[22/Mar/2023:20:31:25] ENGINE Started monitor thread 'SSDP_NOTIFY_THREAD'.
INFO:cherrypy.error:[22/Mar/2023:20:31:25] ENGINE Bus STARTED
INFO:server:Server current run on port: 8428
INFO:main:tag_name: v0.7
ERROR:MPVRenderer:mpv ipc socket start connect
INFO:MPVRenderer:{'event': 'property-change', 'id': 1, 'name': 'volume', 'data': 100.0}
INFO:MPVRenderer:{'event': 'property-change', 'id': 3, 'name': 'pause', 'data': False}
ERROR:SSDPServer:drop membership 192.168.15.190
ERROR:SSDPServer:drop membership 192.168.137.1
INFO:main:ssdp_update_ip
ERROR:SSDPServer:add membership 192.168.15.190
ERROR:SSDPServer:add membership 192.168.137.1

**Comment by xfangfang** [comment]
@Fengqiv 
可以先自行检查一遍：

https://github.com/xfangfang/Macast/wiki/常见问题#在客户端里搜索不到macast

**Comment by Fengqiv** [comment]
@xfangfang 看了这个没能解决，不是端口，不是ap隔离

**Comment by Fengqiv** [comment]
@xfangfang  log中：(2, 'RegDeleteValue', '系统找不到指定的文件。') 是什么错误？

**Comment by xfangfang** [comment]
如果你确定上面的内容不能解决的话，我就不知道原因了。

我不记得这一项具体的内容了，大概是读取系统某些注册表内容没读到，和投屏无关。

---
我简单补充一点，几乎99%的windows用户反馈说手机搜不到，都是防火墙问题。这其中有一大半都认为自己没问题。
另外1%是搞错了投屏协议的

**Comment by Fengqiv** [comment]
我之前可以用，一段时间没用 经历多次系统更新后，最近再用就不行了，且我的防火墙是关了的

**Comment by xfangfang** [comment]
所以你有按照上面提及的相关方式去测试吗？测试的结果是什么呢？

**Comment by Fengqiv** [comment]
OK 解决了，公有网络防火墙没关，我大意了；sorry

**Comment by xfangfang** [comment]
哈哈，我已经很习惯这种类型的反馈啦
