### ISSUE TITLE
[Question] Archlinux  Gnome 上的托盘问题

### ISSUE THREAD

**Issue by icepie** [xfangfang/Macast#17]
## Versions

- System version: Archlinux with Gnome 4 (wayland)
- Processor architecture: x64
- APP version: git

## Problem

感谢作者, 经过测试在我的设备上正常工作

唯一美中不足的就是没有看到托盘显示(看了您的视频来的, 不知道是否为bug)

**Comment by icepie** [comment]
貌似解决了, 十分感谢, 希望能打包一份 archlinux版本的

**Comment by xfangfang** [comment]
我不太清楚这里的托盘显示指的是什么，是运行时状态栏或者说菜单栏没有一个可以点击的图标吗？
可以在terminal中手动运行macast看一看有没有有用的log，一般来说可以运行程序 状态栏就会有图标的。

对于archlinux系统的打包我不是很了解，这个项目使用Github-Actions进行自动构建，可以参考[build-amd64](https://github.com/xfangfang/Macast/blob/7447b2b939861abc35a09532e10efa461b3e9094/.github/workflows/build-macast.yaml#L63)，在构建好二进制文件后，对应archlinux进行打包，欢迎提交代码。
