### ISSUE TITLE
[BUG] Latest release file is identified as damaged on latest MacOS 13.6 Intel

### ISSUE THREAD

**Issue by aiyagari** [xfangfang/Macast#171]
## Versions

- System: (eg:MacOS) MacOS
- System version: 13.6
- Processor architecture: (X86)
- APP version:  v0.7

## Bug recurrence
OS identifies build as damaged and won't load

(How to trigger this bug)

Download .dmg
Drag Macast into Applications folder
Open it

## Additional information

(More description of this bug)
The OS prompts you to delete the file because it says it is damaged.

## Log
No logs because program cannot start.

### MacOS

run this in your terminal:
```
/Applications/Macast.app/Contents/MacOS/Macast
```

Same result when this is run from the terminal

**Comment by xfangfang** [comment]
https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/

https://github.com/xfangfang/wiliwili/blob/yoga/scripts/mac/readme.txt

**Comment by aiyagari** [comment]
Wow.  That fixed it.  Apple is really bad with these messages -- they don't even alert you that it is a quarantine issue.
