### ISSUE TITLE
Add a long press button to play at double speed?

### ISSUE THREAD

**Issue by zzh567** [xfangfang/Macast#174]
I think it will be convenient.

**Comment by xfangfang** [comment]
https://github.com/xfangfang/Macast/wiki/FAQ#how-to-set-personal-configurations-to-mpv

You can set the desired shortcut keys to MPV.

According to mpv's doc: https://mpv.io/manual/stable/#keyboard-control

The default  shortcut key is { and }

```
{ and }
Halve/double current playback speed.
```

**Comment by zzh567** [comment]
Thank you！！ @xfangfang
