### ISSUE TITLE
[BUG] 没有替换播放器的选项

### ISSUE THREAD

**Issue by ec-to** [xfangfang/Macast#175]
## Versions

- System: Windows11 Pro
- System version: 22H2 22621.1702
- Processor architecture: x86
- APP version: V0.7

## Bug recurrence

插件已经放入指定文件夹了，也重启了。没有更换播放器的选项。
播放器相关设置按钮也是灰色的。

![image](https://github.com/xfangfang/Macast/assets/24844835/f8273e4b-17c9-49f1-829f-24666f17be94)

**Comment by xfangfang** [comment]
@ec-to 你的这个截图显示，脚本的大小均为 0KB，所以我认为可能是复制了错误的脚本进来。

**Comment by jiahuangmail** [comment]
我也是遇到这个问题，下载的脚本基本都是0KB，不可用的。但都是在点击软件下的《高级设置》上打开的网页上下载的。如果这下载的都不行，那还有哪里能复制正确的脚本呢？macast简介上说可以获取下载视频的地址。在软件上也找不到。只有停止接受投屏，退出，设置按钮。下载的按钮是没有的。尝试过web下载但是，插件也是0KB
![4b9ca1aca6a5bf95e987bc0bab82be5](https://github.com/xfangfang/Macast/assets/150501972/d17d3b15-d49f-4d10-b560-07aaacba295e)

**Comment by xfangfang** [comment]
@jiahuangmail 我不知道0kb是怎么下载出来的，如果确实有问题，可以把你操作的步骤一步一步描述一遍，最好可以附加截图或者视频。

我能确认的是绝大多数人都没有问题

**Comment by ec-to** [comment]
> @jiahuangmail 我不知道0kb是怎么下载出来的，如果确实有问题，可以把你操作的步骤一步一步描述一遍，最好可以附加截图或者视频。
> 
> 我能确认的是绝大多数人都没有问题

0kb就是通过设置里“高级设置”本地网页里install的

**Comment by xfangfang** [comment]
@ec-to 可以阅读一下readme，里面有写如何手动下载。
macast的插件下载来源是github，在国内的网络环境中可能出现勉强能上github，但是无法下载部分资源的问题。
如果在安装过程中没有弹出来安装成功然后就关闭了应用，可能或许会造成这个现象吧。

**Comment by xfangfang** [comment]
这个问题应该不属于bug，所以先暂时关闭了

**Comment by ec-to** [comment]
> @ec-to 可以阅读一下readme，里面有写如何手动下载。 macast的插件下载来源是github，在国内的网络环境中可能出现勉强能上github，但是无法下载部分资源的问题。 如果在安装过程中没有弹出来安装成功然后就关闭了应用，可能或许会造成这个现象吧。

我是翻墙的环境，按道理说应该不会呀。还是建议加一个下载后校验后再自动重启。

**Comment by xfangfang** [comment]
@ec-to https://github.com/xfangfang/Macast/commit/23ff629d089aecb97904c2ce47789a14d8790305

dev_test 分支的代码应该增加了windows代理的支持，考虑到这是一个开源项目，相比于建议更愿意接收pr，感谢。

**Comment by xfangfang** [comment]
目前这个项目应该处在还能用但是没有新功能增加的状态中，对于我现在来说会更愿意用c++ 和 quickjs重新实现一遍而不是在python上挣扎，python做这个事太不稳定了，对不同平台的适配也不好搞（搞到底层还是需要c/c++），应用开启速度也不是很让人满意。
如果有兴趣用c++重写的话欢迎一起开发，我在其他项目里也有需要dlna的部分，那时候顺便用c++做了个比较容易使用的跨平台的dlna库，ui可以用qt，插件部分目前的想法是用quickjs和c++代码整合。
