### ISSUE TITLE
self.protocol.get_state_title() 显示的是上次投屏的

### ISSUE THREAD

**Issue by sysdefault** [xfangfang/Macast#182]
## Versions

- System version: Linux
- Processor architecture: X86
- APP version: v0.7

## Problem

大佬你好，自己写了个 renderer.py ，播放器标题这里 title = self.protocol.get_state_title()
但是得到的是上次投屏的标题（上次、这次，两次是不同内容的投屏）
手动结束再重新投屏同一个内容，才能正常显示这个内容的标题。可复现，每次都是这样。

并且，重新启动Macast后的首次投屏 self.protocol.get_state_title() 为空

在终端运行排查接收到的投屏信息，每次投屏<dc:title>没有问题是实时的，请问大佬怎么解决?

**Comment by xfangfang** [comment]
你可以在 set_media_title 函数接收到实时的标题。

或者如果一定要在获取播放链接的同时获取标题，可以在 set_media_title 函数内获取播放链接。

当然上面的行为依赖于内部实现，未来可能会更改。

**Comment by xfangfang** [comment]
具体调用的逻辑可以看下面的代码，能看到renderer 相关函数的调用顺序。

https://github.com/xfangfang/Macast/blob/121add3a8a70edb77e33aeab1ec88aeff27f49fc/macast/protocol.py#L682

未来应该会把 renderer 相关的调用放在 set state那一堆调用之后，这样可以通过获取protocol的内部state来在任意一个renderer调用内获取到实时的信息

**Comment by sysdefault** [comment]
感谢
