### ISSUE TITLE
It won't install on Ubuntu

### ISSUE THREAD

**Issue by trappedinspacetime** [xfangfang/Macast#2]
First of all, thank you for making this project. I am on Ubuntu 20.04 platform. I tried to install it but it fails to install `pyobj` library since it's platform specific https://github.com/ronaldoussoren/pyobjc/issues/291
Is there a way to install it on Ubuntu?

**Comment by xfangfang** [comment]
@trappedinspacetime 
This project is only for MacOS, I don't have enough time to add the support of other systems currently. However, you can change the code to make this run in a terminal temporarily.

1. Change SETTING_DIR in ***utils.py line 21***
    SETTING_DIR is used to store configuration files. Change this to a directory available on Ubuntu
2. Change MPV parameters in ***mpv.py line 512 to 527***
    - Modify the path of MPV to the path of MPV in your system. You can try ```mpv = 'mpv'```
    - Modify the startup parameters of MPV (the startup parameters in the code contain many MacOS only contents now)
3. Remove ***rumps*** from Macast.py and requirements.txt
    - Remove rumps from ***requirements.txt***
    - Remove ```import rumps``` from ***Macast.py line 6***
    - Remove Macast class  from ***Macast.py line 121***
    - Modify the startup code in ***Macast.py line 189***
    ```python
    if __name__ == '__main__':
        startCherrypy()
    ```
 
After these modifications, the code should be able to run on Linux. And if you can wait, I will adapt this application to gnome's menubar later.(maybe a week)

**Comment by xfangfang** [comment]
@trappedinspacetime 
I just ran it successfully on the status bar of Ubuntu 20.04. If you have time, can you test it on your computer?

you need: 
1. pip install pystray
2. make sure you can use ***gi***:

```
$ python3
Python 3.7.10 (default, Jun  3 2021, 17:51:26)
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>>
```
if there is something wrong, try: ***sudo apt-get install python3-gi***
if you use conda, check this https://stackoverflow.com/a/40303128


3. python3 Macast.py

Hope everything goes well. I'm not sure how to package a deb application. If you know anything, feel free to pull request

**Comment by xfangfang** [comment]
Because many Linux users have reported that they can run normally, close this issue.
