### ISSUE TITLE
[NEW FEATURE] 在我打包了archlinux版本之后, 想让作者改进的地方

### ISSUE THREAD

**Issue by icepie** [xfangfang/Macast#20]
## New feature

- 配置文件 `macast_setting.json` 的路径应位于 `~/.config/macast` (规范)

- 可以抛弃 `py2app` 和 `pyinstaller` 的打包方式, 直接上架 `pip` 源中 (方便 `brew` 和 `pacman` 之类的后期打包)

## Additional context

感谢作者的无私奉献 !

这是个人在打包该项目的 [aur](https://aur.archlinux.org/packages/macast-git/) 时想到的一些改进, 希望采纳!

**Comment by xfangfang** [comment]
感谢提醒，配置文件路径是不是应该为：~/.config/macast/macast_setting.json  

上架pip这个注意确实不错，可以方便不少，就是目前还不支持命令行参数，最近时间也不充裕，感觉还需要再过些日子吧，不过可以算作是计划中的安排了。
感谢感谢

**Comment by icepie** [comment]
> 感谢提醒，配置文件路径是不是应该为：~/.config/macast/macast_setting.json
> 
> 上架pip这个注意确实不错，可以方便不少，就是目前还不支持命令行参数，最近时间也不充裕，感觉还需要再过些日子吧，不过可以算作是计划中的安排了。
> 感谢感谢

对的! 全平台都可以使用这个目录, 命令行确实应该设计一下~

现在我在aur里写了个名为`macast`的bash脚本作为desktop的入口和命令行启动方式

辛苦作者了!

**Comment by WhiredPlanck** [comment]
> 感谢提醒，配置文件路径是不是应该为：~/.config/macast/macast_setting.json

这个是 freedesktop.org 的 XDG Base 目录规范，可以参考 https://wiki.archlinux.org/title/XDG_Base_Directory 和里面的相关链接

**Comment by xfangfang** [comment]
@icepie dev分支目前支持pip安装，安装后可通过命令行调用—— `macast-cli` 和 `macast-gui` 

```shell
# 测试安装：
pip install git+https://github.com/xfangfang/Macast.git@dev
```

**Comment by icepie** [comment]
> @icepie dev分支目前支持pip安装，安装后可通过命令行调用—— `macast-cli` 和 `macast-gui`
> 
> ```shell
> # 测试安装：
> pip install git+https://github.com/xfangfang/Macast.git@dev
> ```

收到, 待我回去更换一下打包方式

**Comment by icepie** [comment]
aur 这边已更新(pip 的打包方式了) , 貌似还有点小问题

- `i18n` 似乎未能成功加载
- 点击 about 跳转浏览器依赖于 `sensible-utils` 感觉并不是最佳方案 (有空我帮忙看看用啥解决好点)

**Comment by xfangfang** [comment]
i18n的问题，是我没有放在pip的包内，主要是仓库提供的是i18n的po文件，运行需要编译成mo，这就需要不同系统间有一个统一的编译操作，感觉比较麻烦，索性pip运行就不放翻译了。
跳转浏览器的操作，是因为python的webbrowser在pyinstaller编译后linux系统下找不到系统内置的浏览器。
都是无奈之举

**Comment by icepie** [comment]
> i18n的问题，是我没有放在pip的包内，主要是仓库提供的是i18n的po文件，运行需要编译成mo，这就需要不同系统间有一个统一的编译操作，感觉比较麻烦，索性pip运行就不放翻译了。
> 跳转浏览器的操作，是因为python的webbrowser在pyinstaller编译后linux系统下找不到系统内置的浏览器。
> 都是无奈之举

确实如此, 希望咱能抽空优化一下

**Comment by xfangfang** [comment]
抱歉，打扰一下
昨晚更新新增了多网卡支持，有些用户会因为虚拟网卡或者是多网卡的问题，导致搜索不到Macast，所以需要检测多网卡，找来找去找到了这个：netifaces，这个包的github地址在：https://github.com/al45tair/netifaces

现在linux用到的两个包 pystray 和 pyperclip是我修改过的，原本的包在某些系统上会出现的小问题（我的修复都是从这两个项目的pull requests里整合的，明明这两个库都有作者运营不知道为什么不采用）。刚刚虚拟机运行了一下manjaro，看起来pystary原版在manjaro上是没问题的，但是pyperclip还是有些问题。

在投视频之后点击菜单项可以复制视频，这种情况下原版的pyperclip会报错，我更改的这一版支持了gtk3+，刚刚测试pip重新安装这个就解决了: https://github.com/xfangfang/pyperclip

对于怎么做aur的包所知甚少，感谢付出，在wiki中添加了相关说明，欢迎指正修改：https://github.com/xfangfang/Macast/wiki/Installation#aur

ps. 现在可以把分支换到main了

**Comment by icepie** [comment]
对于 `aur` 的打包来说, 习惯上是允许存在 `main` 和 `dev` 两个版本的, 即 `macast` 和 `macast-git`

**Comment by xfangfang** [comment]
哦哦 了解啦 感谢科普

**Comment by icepie** [comment]
看了一下 `pyperclip` 这边的问题: https://github.com/asweigart/pyperclip/pull/182

打包起来确实遇到难受, 可以考虑暂时先使用 `xclip` 之类的命令先解决一下么

因为 `pip` 这类打包方式的话会牵扯到和社区源里的 [python-pyperclip](https://archlinux.org/packages/community/any/python-pyperclip/) 产生冲突....

比较无奈...

**Comment by xfangfang** [comment]
看起来主要问题都解决了，先把这个issue关闭
