### ISSUE TITLE
Win11下，iPhoneXR中BILIBILI无法投屏直播

### ISSUE THREAD

**Issue by Yang-jianye** [xfangfang/Macast#21]
win11下，iPhoneXR里BILIBILI普通的视频可以投屏，但是不能投频直播。会报错

**Comment by xfangfang** [comment]
报什么错呢？如果是反馈报错的话，可以下载windows debug版客户端，然后在new issue的时候选择 **bug report** 里面有详细的反馈说明。
我这边测试是没问题的，就是可能要多等一会就搜到了，这个问题我稍后再测测，看看可能是什么原因

**Comment by xfangfang** [comment]
同一局域网下，搜索Macast很费力，但是这是开启电视的投屏服务后就可以立刻搜索到电视和Macast了，这里确实是有点问题，稍进一步检查

**Comment by Yang-jianye** [comment]
## Versions

- System: (Windows11 )
- System version: (Windows11 Insider Preview 10.0.22000.160)
- Processor architecture: (X86)
- APP version: ( v0.5)

## Bug recurrence

IphoneXR投屏直播视频

## Additional information

(More description of this bug)

## Log

Starting Macast from terminal to get logs.

Macast Loading Language: zh_CN
MPV started
Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "macast\ssdp.py", line 72, in run
OSError: [WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。

ERROR:Render:mpv ipc socket start connect
INFO:Render:{'event': 'property-change', 'id': 1, 'name': 'volume', 'data': 100.0}
INFO:Render:{'event': 'property-change', 'id': 3, 'name': 'pause', 'data': False}
DEBUG:Macast:tag_name: v0.5
INFO:Render:AVTransport_SetAVTransportURI {'InstanceID': '0', 'CurrentURI': 'http://d1--cn-gotcha03.bilivideo.com/live-bvc/147544/live_23496660_9356207_minihevc.flv?expires=1629698294&len=0&oi=1905003387&pt=ios&qn=250&trid=1000d97cf6510b2b4630939577487db60250&sigparams=cdn,expires,len,oi,pt,qn,trid&cdn=cn-gotcha03&sign=c661f0490c2139c3b2e1ce5318e18819&p2p_type=0&src=5&sl=1&free_type=0&sk=18232a4fcc82e4c037c33d7e083619b4', 'CurrentURIMetaData': '<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/"><item id="123" parentID="-1" restricted="1"><res protocolInfo="http-get:*:video/*:*;DLNA.ORG_OP=01;DLNA.ORG_FLAGS=01700000000000000000000000000000">http://d1--cn-gotcha03.bilivideo.com/live-bvc/147544/live_23496660_9356207_minihevc.flv?expires=1629698294&amp;len=0&amp;oi=1905003387&amp;pt=ios&amp;qn=250&amp;trid=1000d97cf6510b2b4630939577487db60250&amp;sigparams=cdn,expires,len,oi,pt,qn,trid&amp;cdn=cn-gotcha03&amp;sign=c661f0490c2139c3b2e1ce5318e18819&amp;p2p_type=0&amp;src=5&amp;sl=1&amp;free_type=0&amp;sk=18232a4fcc82e4c037c33d7e083619b4</res><upnp:storageMedium>UNKNOWN</upnp:storageMedium><upnp:writeStatus>UNKNOWN</upnp:writeStatus><dc:title>01</dc:title><upnp:class>object.item.videoItem</upnp:class></item></DIDL-Lite>'}
INFO:Render:http://d1--cn-gotcha03.bilivideo.com/live-bvc/147544/live_23496660_9356207_minihevc.flv?expires=1629698294&len=0&oi=1905003387&pt=ios&qn=250&trid=1000d97cf6510b2b4630939577487db60250&sigparams=cdn,expires,len,oi,pt,qn,trid&cdn=cn-gotcha03&sign=c661f0490c2139c3b2e1ce5318e18819&p2p_type=0&src=5&sl=1&free_type=0&sk=18232a4fcc82e4c037c33d7e083619b4
INFO:Render:{'event': 'start-file', 'playlist_entry_id': 1}
DEBUG:Macast:mpv_av_uri: http://d1--cn-gotcha03.bilivideo.com/live-bvc/147544/live_23496660_9356207_minihevc.flv?expires=1629698294&len=0&oi=1905003387&pt=ios&qn=250&trid=1000d97cf6510b2b4630939577487db60250&sigparams=cdn,expires,len,oi,pt,qn,trid&cdn=cn-gotcha03&sign=c661f0490c2139c3b2e1ce5318e18819&p2p_type=0&src=5&sl=1&free_type=0&sk=18232a4fcc82e4c037c33d7e083619b4
index:  0
INFO:Render:AVTransport_Play {'InstanceID': '0', 'Speed': '1'}
INFO:Render:{'event': 'tracks-changed'}
INFO:Render:{'event': 'tracks-changed'}
INFO:Render:{'event': 'metadata-update'}
INFO:Render:{'event': 'video-reconfig'}
INFO:Render:{'event': 'video-reconfig'}
INFO:Render:{'event': 'track-switched'}
INFO:Render:{'event': 'audio-reconfig'}
INFO:Render:{'event': 'audio-reconfig'}
INFO:Render:{'event': 'file-loaded'}
INFO:Render:{'event': 'audio-reconfig'}
INFO:Render:{'event': 'tracks-changed'}
INFO:Render:{'event': 'end-file', 'reason': 'error', 'playlist_entry_id': 1, 'file_error': 'something happened'}
DEBUG:Macast:mpv_av_stop
INFO:Render:{'event': 'idle'}

**Comment by Yang-jianye** [comment]
> 报什么错呢？如果是反馈报错的话，可以下载windows debug版客户端，然后在new issue的时候选择 **bug report** 里面有详细的反馈说明。
> 我这边测试是没问题的，就是可能要多等一会就搜到了，这个问题我稍后再测测，看看可能是什么原因

好像是和spacedesk冲突了，关掉spacedesk就好了

**Comment by xfangfang** [comment]
如果是冲突的话，应该不会出现只有直播视频投屏有问题，普通视频没问题的情况的。

**Comment by chengyuhui** [comment]
B站移动端的直播和视频投屏（包括Android和iOS）应该并不是同一个组件，直播投屏在两个平台上都不是非常稳定，官方的电视应用都经常不能正常投屏，估计是B站自己的问题。

**Comment by xfangfang** [comment]
经过今天更新后，这个应用现在应该已经比较稳定了，先把这个20天前的issue关闭，如果还有问题的话可以重新再打开
