### ISSUE TITLE
什么时候加入安卓版呀

### ISSUE THREAD

**Issue by OXERIS** [xfangfang/Macast#22]
## New feature
有开发andriod版本的想法吗？这样一些旧手机就可以用了，一些电视盒子带广告，也很难用

## Additional context
(Add any other context or screenshots about the feature request here.)

**Comment by icepie** [comment]
安卓已经有很多 **DLNA** 服务端了...

**Comment by xfangfang** [comment]
安卓端或许可以试试kodi? bubbleUPnP? 或者神秘改版的乐播投屏。只是说dlna投屏的话，已经有很多可用的方案了。这个软件用python完成并打包的，老设备估计运行起来速度不行也不是很方便转向移动端的。
开始是写着玩，想先用python试试，然后再用go重写方便转移到更多的平台，后来鸽了。可能未来会再开一个仓库用go重写一遍，到时候如果支持了更多的协议的话，确实是可能会支持到安卓的。

为了避免干扰大家看其他issue，先暂时把这个issue关闭了，也欢迎继续讨论。
