### ISSUE TITLE
[Question] 无法使用

### ISSUE THREAD

**Issue by XwumingX** [xfangfang/Macast#32]
## Versions

- System version: Windows 10 Pro 21H1 19043.1165
- APP version:移动端哔哩哔哩 网易云 MIUI相册

## Problem
手机直接找不到，电脑的其他DLAN工具正常
手机访问不了1068
防火墙已排除
路由器小米4A千兆版
电脑的媒体流选项中可以找到酷狗和Windows Media Player的播放器但并找不到Macast

日志如下
Macast Loading Language: zh_CN
MPV started
ERROR:Render:stoping mpv
ERROR:Render:sendCommand: 'NoneType' object has no attribute 'send_bytes'
ERROR:Render:cannot send command quit to mpv
ERROR:Render:stoping mpv
ERROR:Render:sendCommand: 'NoneType' object has no attribute 'send_bytes'
ERROR:Render:cannot send command quit to mpv
ERROR:Render:mpv ipc socket start connect
INFO:Render:{'event': 'property-change', 'id': 1, 'name': 'volume', 'data': 100.0}
INFO:Render:{'event': 'property-change', 'id': 3, 'name': 'pause', 'data': False}
DEBUG:Macast:tag_name: v0.5
ERROR:Render:mpv ipc stopped
ERROR:Render:sendCommand: handle is closed
ERROR:Render:cannot send command quit to mpv
ERROR:Render:sendCommand: handle is closed
ERROR:Render:cannot send command quit to mpv
ERROR:Render:sendCommand: handle is closed
ERROR:Render:cannot send command quit to mpv
ERROR:Render:sendCommand: handle is closed
ERROR:Render:cannot send command quit to mpv
ERROR:Render:sendCommand: handle is closed
ERROR:Render:cannot send command quit to mpv

**Comment by xfangfang** [comment]
这个版本添加了端口检测，可以尝试看看
https://github.com/xfangfang/Macast/actions/runs/1192223767

**Comment by xfangfang** [comment]
Closed due to no response
