### ISSUE TITLE
[BUG] 无法退出

### ISSUE THREAD

**Issue by XwumingX** [xfangfang/Macast#33]
## Versions

- System: Windows 10 Pro 21H1 19043.1165
- APP version: Macast v0.5

## Bug recurrence

任务栏右键，选择“停止接受投屏”和“退出”后图标都在并且无法再右键（右键无反应）任务管理器显示有两个进程在后台

## Log

Macast Loading Language: zh_CN
MPV started
ERROR:Render:stoping mpv
ERROR:Render:sendCommand: 'NoneType' object has no attribute 'send_bytes'
ERROR:Render:cannot send command quit to mpv
ERROR:Render:stoping mpv
ERROR:Render:sendCommand: 'NoneType' object has no attribute 'send_bytes'
ERROR:Render:cannot send command quit to mpv
ERROR:Render:mpv ipc socket start connect
INFO:Render:{'event': 'property-change', 'id': 1, 'name': 'volume', 'data': 100.0}
INFO:Render:{'event': 'property-change', 'id': 3, 'name': 'pause', 'data': False}
DEBUG:Macast:tag_name: v0.5
ERROR:Render:mpv ipc stopped
ERROR:Render:sendCommand: handle is closed
ERROR:Render:cannot send command quit to mpv
ERROR:Render:sendCommand: handle is closed
ERROR:Render:cannot send command quit to mpv
ERROR:Render:sendCommand: handle is closed
ERROR:Render:cannot send command quit to mpv
ERROR:Render:sendCommand: handle is closed
ERROR:Render:cannot send command quit to mpv
ERROR:Render:sendCommand: handle is closed
ERROR:Render:cannot send command quit to mpv

**Comment by xfangfang** [comment]
我感觉，最新的测试版应该会解决这个问题：https://github.com/xfangfang/Macast/actions/runs/1200349562

**Comment by xfangfang** [comment]
Closed due to no response
