### ISSUE TITLE
腾讯视频貌似无法搜索到

### ISSUE THREAD

**Issue by shelken** [xfangfang/Macast#34]
ios15，腾讯视频，iPhone11，不知道是腾讯限制还是什么问题，腾讯视频一直无法搜索到。在爱奇艺和b站都是正常的。补充下：在mac mini m1上使用作者的方法编译的程序

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by xfangfang** [comment]
这是第一个关于腾讯视频搜索不到的反馈，请根据issue模板重新报告bug。

下载这个调试版可以获得更多log：https://github.com/xfangfang/Macast/actions/runs/1162138219
