### ISSUE TITLE
[BUG] 腾讯视频无法搜索到

### ISSUE THREAD

**Issue by shelken** [xfangfang/Macast#35]
## Versions

- System: macOS 11
- System version: 11.5.2
- Processor architecture: arm
- APP version: v0.5

## Bug recurrence
腾讯视频无法搜索到
## Additional information

ios15，腾讯视频，iPhone11，
不知道是腾讯限制还是什么问题，腾讯视频一直无法搜索到。在爱奇艺和b站都是正常的。
补充下：在mac mini m1上使用作者的方法编译的程序

## Log

无

**Comment by xfangfang** [comment]
要有log的呀！就是为了看log才要你重发的，拉了代码的话可以切到morelog分支，然后贴运行之后腾讯视频搜索时候的log，因为好像有人反馈过腾讯视频是可以正常使用的。

**Comment by shelken** [comment]
不太懂如何看日志操作，麻烦详细点，运行后日志输出在哪个文件

**Comment by xfangfang** [comment]
我在issue模板里有写呀，可以详细看一看。
如果你是拉代码自己编译的，可以切换到morelog分支，然后直接从源码运行，查看terminal输出。

在项目根目录下运行：
```shell
git checkout -b morelog origin/morelog
python Macast.py
```
然后把log贴过来
之后可以再切换回主分支复原
```git checkout main```

**Comment by shelken** [comment]
> 我在issue模板里有写呀，可以详细看一看。
> 如果你是拉代码自己编译的，可以切换到morelog分支，然后直接从源码运行，查看terminal输出。
> 
> 在项目根目录下运行：
> 
> ```shell
> git checkout -b morelog origin/morelog
> python Macast.py
> ```
> 
> 然后把log贴过来
> 之后可以再切换回主分支复原
> `git checkout main`

以下为使用腾讯视频时点击投屏时日志的变化。很奇怪，因为这个192.168.6.12本身是电脑的ip。

`DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b::urn:schemas-upnp-org:device:MediaRenderer:1
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b::urn:schemas-upnp-org:service:RenderingControl:1
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b::urn:schemas-upnp-org:service:ConnectionManager:1
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b::urn:schemas-upnp-org:service:AVTransport:1
INFO:SSDPServer:SSDP command M-SEARCH * - from 192.168.6.12:50442
DEBUG:SSDPServer:M-SEARCH *
DEBUG:SSDPServer:b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nMAN: "ssdp:discover"\r\nMX: 1\r\nST: urn:dial-multiscreen-org:service:dial:1\r\nUSER-AGENT: Google Chrome/92.0.4515.159 Mac OS X\r\n\r\n'
INFO:SSDPServer:Discovery request from (192.168.6.12,50442) for urn:dial-multiscreen-org:service:dial:1
INFO:SSDPServer:SSDP command M-SEARCH * - from 192.168.6.12:50442
DEBUG:SSDPServer:M-SEARCH *
DEBUG:SSDPServer:b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nMAN: "ssdp:discover"\r\nMX: 1\r\nST: urn:dial-multiscreen-org:service:dial:1\r\nUSER-AGENT: Google Chrome/92.0.4515.159 Mac OS X\r\n\r\n'
INFO:SSDPServer:Discovery request from (192.168.6.12,50442) for urn:dial-multiscreen-org:service:dial:1
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b::upnp:rootdevice
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b::urn:schemas-upnp-org:device:MediaRenderer:1
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b::urn:schemas-upnp-org:service:RenderingControl:1
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b::urn:schemas-upnp-org:service:ConnectionManager:1
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b::urn:schemas-upnp-org:service:AVTransport:1
INFO:SSDPServer:SSDP command M-SEARCH * - from 192.168.6.12:50442
DEBUG:SSDPServer:M-SEARCH *
DEBUG:SSDPServer:b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nMAN: "ssdp:discover"\r\nMX: 1\r\nST: urn:dial-multiscreen-org:service:dial:1\r\nUSER-AGENT: Google Chrome/92.0.4515.159 Mac OS X\r\n\r\n'
INFO:SSDPServer:Discovery request from (192.168.6.12,50442) for urn:dial-multiscreen-org:service:dial:1
INFO:SSDPServer:SSDP command M-SEARCH * - from 192.168.6.12:50442
DEBUG:SSDPServer:M-SEARCH *
DEBUG:SSDPServer:b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nMAN: "ssdp:discover"\r\nMX: 1\r\nST: urn:dial-multiscreen-org:service:dial:1\r\nUSER-AGENT: Google Chrome/92.0.4515.159 Mac OS X\r\n\r\n'
INFO:SSDPServer:Discovery request from (192.168.6.12,50442) for urn:dial-multiscreen-org:service:dial:1
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b::upnp:rootdevice
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b::urn:schemas-upnp-org:device:MediaRenderer:1
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b::urn:schemas-upnp-org:service:RenderingControl:1
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b::urn:schemas-upnp-org:service:ConnectionManager:1
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b::urn:schemas-upnp-org:service:AVTransport:1
DEBUG:SSDPServer:Sending alive notification for uuid:9811da03-fc68-4313-b268-978ff84de92b::upnp:rootdevice`

**Comment by shelken** [comment]
除此之外没有任何日志的变化

**Comment by shelken** [comment]
而我手机ip为224。使用其他投的时候Discovery request from (192.168.6.224)都是对的

**Comment by xfangfang** [comment]
这个log只有大概10s的样子，腾讯视频我刚刚在我的ipad上是正常的，这个原因我就不太清楚了，可以多等会，看看有没有来自手机ip的 M-SEARCH，类似这种语句的log “INFO:SSDPServer:SSDP command M-SEARCH * - from 192.168.6.12:50442”

现在的M-SEARCH是电脑上chrome发出的，可以不用理会。

测试时候可以试试把手机上其他视频软件都关掉只留腾讯视频，防止干扰

**Comment by shelken** [comment]
删除腾讯视频后，重新打开后正常了。打开后看到弹出“允许发现本地网络”提示，想起来可能之前把这个选项关了，才导致的
