### ISSUE TITLE
[NEW FEATURE] Hello, can you add AirPlay support?

### ISSUE THREAD

**Issue by zxkmm** [xfangfang/Macast#36]
您好，请问是否考虑支持Airplay（隔空播放）？
## New feature
(type your idea here)
因为iOS系统很多app只支持AirPlay，我以前在windows桌面端一直使用kodi作为AirPlay接收端，但是kodi对AirPlay的支持只到iOS9。希望能增加AirPlay支持。感谢！

**Comment by xfangfang** [comment]
airplay的支持一定会做，但是可能会比较困难要多等等了

**Comment by zxkmm** [comment]
> airplay的支持一定会做，但是可能会比较困难要多等等了

感谢！🙏
