### ISSUE TITLE
[NEW FEATURE] Request Android support

### ISSUE THREAD

**Issue by sceraser** [xfangfang/Macast#38]
## New feature
Support Android TV/Phone

## Additional context
众所周知，不是所有安卓设备都是DLNA发射端，还有安卓盒子需要作为DLNA的接收端，目前的主流方案都带有大量广告，非常影响使用

**Comment by xfangfang** [comment]
这个应用使用python开发，移植到安卓难度极大且运行效率不高，可以试试kodi
