### ISSUE TITLE
[Question]How to modify the default video player

### ISSUE THREAD

**Issue by TuRan-sino** [xfangfang/Macast#40]
## Versions

- System version: windows
- Processor architecture: (eg:X86)
- APP version: (eg: v0.2)

## Problem
How to modify the default video player

## define 
I am noticed that there is a video player named mpv. <br>What i can do if i want to use potplayer as my default video player?

**Comment by xfangfang** [comment]
Check this: https://github.com/xfangfang/Macast/wiki/Custom-Renderer

Any questions are welcome to discuss.

**Comment by xfangfang** [comment]
PotPlayer plug-in for Macast is avaliable now.
https://github.com/xfangfang/Macast/wiki/FAQ#how-to-use-third-party-player-plug-in

Please give me some response when you are free.

**Comment by TuRan-sino** [comment]
Thanks a lot

**Comment by xfangfang** [comment]
close this issue, feel free to open a new issue if you have any questions.
