### ISSUE TITLE
[Question] 启动失败

### ISSUE THREAD

**Issue by kangbeicai** [xfangfang/Macast#42]
## Versions

- System version: Windows 10  21H1 19043.1165
- Processor architecture: X86
- APP version: V0.5-debug

## Problem
无法投屏,debug日志好像报错了?
![微信截图_20210906215408](https://user-images.githubusercontent.com/57837294/132228346-a0a2e54b-192f-49f3-94a1-fe506d202cc5.png)

(your problem description here)

**Comment by xfangfang** [comment]
看log是正常启动的

如果搜索不到，请先看：[常见问题与解决方法](https://github.com/xfangfang/Macast/blob/main/README_ZH.md#常见问题与解决办法)

解决不了您的问题的话可以尝试看看这个： https://github.com/xfangfang/Macast/issues/19#issuecomment-913114786

**Comment by xfangfang** [comment]
您好，有没有解决您的问题呢？是不是给个反馈会更礼貌一些

**Comment by kangbeicai** [comment]
> 您好，有没有解决您的问题呢？是不是给个反馈会更礼貌一些

抱歉， 我是中午加群来咨询的，因为中午在群里反馈过了，刚想起来把这个issue关掉。
我的问题出在windows开启upnp后1900端口被占用，希望这一点能够写到安装说明里去。
但是关闭UPDP后仍然无法寻找到设备，使用链接里改过的exe文件后可以正常运行。

**Comment by xfangfang** [comment]
好的 谢谢～
