### ISSUE TITLE
[BUG] win7搜不到设备

### ISSUE THREAD

**Issue by joshatt** [xfangfang/Macast#44]
## Versions

- System: (eg:MacOS)          win7
- System version: (eg:11.4)     旗舰版sp1
- Processor architecture: (eg:X86)  x64
- APP version: (eg: v0.2)   0.5

## Bug recurrence

win7笔记本, 电信宽带......下载后运行正常出现托盘图标, 没有闪退. 用安卓手机上的"v影"软件测试, 搜不到设备. 而投屏到安卓TV正常.
安卓浏览器访问电脑: http:192.168.1.5:1068, 看到hello world None
改用debug版本,  如图
https://files.catbox.moe/9tt4w8.jpg
然后等到出现托盘图标, 这下可以搜索到设备了, 然后尝试投屏, 托盘图标弹出小提示: load failed:
https://files.catbox.moe/0m5tic.jpg

## Additional information

(More description of this bug)

## Log

Starting Macast from terminal to get logs.

### MacOS

run this in your terminal:
```
/Applications/Macast.app/Contents/MacOS/Macast
```

### Windows

download debug version of this application: [Download link](https://github.com/xfangfang/Macast/releases/latest)

### Linux

```
python Macast.py
```

### PasteBoard
```
# then paste your log here

```

**Comment by xfangfang** [comment]
win7实际是没有经过我验证可用的，不过有一些用户反馈说win7没问题

看log，应用接收到的视频链接为：https://vod4.buycar5.cn/20210611/FTgaD2Hw/index.m3u8
这个链接我确实是无法访问的，所以有没有可能是视频源的问题呢？

但是说投安卓电视没问题又让人感觉奇怪，建议先用国内主流的视频软件测试看看能不能用，等我有空时候下个win7和您用的软件再测试看看吧

**Comment by joshatt** [comment]
> win7实际是没有经过我验证可用的，不过有一些用户反馈说win7没问题
> 
> 看log，应用接收到的视频链接为：https://vod4.buycar5.cn/20210611/FTgaD2Hw/index.m3u8
> 这个链接我确实是无法访问的，所以有没有可能是视频源的问题呢？
> 
> 但是说投安卓电视没问题又让人感觉奇怪，建议先用国内主流的视频软件测试看看能不能用，等我有空时候下个win7和您用的软件再测试看看吧

这个片子用TV测试了, 能播放. 但这个m3u8链接, 在我电脑上用黑鸟播放器测试, 确实说无效链接. 不懂了.
现在的问题是, debug版可以搜索到设备, 正式版搜不到.....说明问题还未涉及到影片链接这一步?
我再试试其他视频软件.
多谢解答

**Comment by xfangfang** [comment]
如果debug版是从github release下载的话，那么和正式版代码都是一模一样的，就是debug版开启了log窗口而已。

有很多盗版视频软件用的m3u8貌似不是标准的m3u8，收到过几个反馈说m3u8播放不了，后来发现都是同样的问题。
他们提供的链接，mpv和vlc都是无法播放的，可能是tv端对此作了特殊优化吧

**Comment by joshatt** [comment]
> 如果debug版是从github release下载的话，那么和正式版代码都是一模一样的，就是debug版开启了log窗口而已。
> 
> 有很多盗版视频软件用的m3u8貌似不是标准的m3u8，收到过几个反馈说m3u8播放不了，后来发现都是同样的问题。
> 他们提供的链接，mpv和vlc都是无法播放的，可能是tv端对此作了特殊优化吧

这样啊, 多谢

**Comment by xfangfang** [comment]
https://github.com/xfangfang/Macast/actions/runs/1221305105
这个版本修复了在多网卡或存在虚拟网卡的情况下无法搜索到设备的问题，希望对您有帮助，期待反馈

**Comment by xfangfang** [comment]
经过测试主流视频软件在win7上都是可以接收到投屏的，所以应该可以先关闭这个issue了
