### ISSUE TITLE
[IINA支持]推荐播放器加入对IINA的支持

### ISSUE THREAD

**Issue by lty2008one** [xfangfang/Macast#5]
IINA是macOS系统上一个很好用的视频播放器，支持各种文件以及流媒体播放，如果能够支持投屏调用IINA打开也可以更方便地使用macOS系统提供的小窗播放功能（自动吸附边角，不遮挡推送等）

**Comment by xfangfang** [comment]
I'm not sure if iina can get app control from the command line. If it can, supporting iina will be an exciting feature.

**Comment by lty2008one** [comment]
> I'm not sure if iina can get app control from the command line. If it can, supporting iina will be an exciting feature.

https://github.com/xjbeta/iina-plus
看看这个？iina-plus可以调用iina打开解析过的流

**Comment by lty2008one** [comment]
> I'm not sure if iina can get app control from the command line. If it can, supporting iina will be an exciting feature.

看了一下，可以用这个命令访问到iina的命令行操作
/Applications/IINA.app/Contents/MacOS/iina-cli --help

**Comment by lty2008one** [comment]
本来准备尝试自己写一下，结果clone了看了一下，基本没有注释XD

**Comment by xfangfang** [comment]
This project is still in the early stages of development, you can check **macast/mpv.py MPVRender class** for add iina support.

**Comment by xfangfang** [comment]
我考虑了一下，感觉增加iina的支持目前对这个项目来说有些费劲。
一方面是增加维护的难度，使用mpv可以很方便的完成跨平台的需求，开发时候做很少的跨平台测试即可。添加iina支持后则需要一直注意mac端与其他平台的适配性以及mpv功能与iina的适配性，对于这个项目目前的维护者（几乎就我自己）来说开发测试时间不太充裕；
另外一方面iina不是为了作为视频播放的组件设计的，所以对iina的控制我猜会很麻烦；
mpv拥有强大的脚本支持这个项目未来在播放器上增加更多的功能，而iina对这个项目的帮助貌似只是多了小窗功能，和开发量相比有些得不偿失。
当然如果你有维护的兴趣的话，咱们可以开一个专门的iina分支，关于代码上的任何问题都欢迎讨论～

**Comment by xfangfang** [comment]
在重构了一部分代码之后，目前macast可以支持更多的播放器了，最新代码在dev分支，目前只完美支持mpv，在添加了更多的播放器之后，未来会在前端增加播放器的选择功能。

一个简单的IINA示例在这里：https://github.com/xfangfang/Macast/wiki/Custom-Renderer#example1-iina
欢迎丰富更多的功能
