### ISSUE TITLE
[NEW FEATURE] 能否开放自定义设备名称

### ISSUE THREAD

**Issue by sorosunrain** [xfangfang/Macast#50]
## New feature
如题，想改酷点的名字

**Comment by sorosunrain** [comment]
发现刚发布的版本已经支持！

**Comment by xfangfang** [comment]
我正在写这个文档，下载最新的版本v0.6 点击设置中的 **打开配置文件目录** （类似的名字），然后就能看到具体怎么改啦

**Comment by sorosunrain** [comment]
@xfangfang 嗯，看到了，但貌似设置成中文崩溃

**Comment by xfangfang** [comment]
确实诶，可以试试中文转unicode，比如：\u6d4b\u8bd5

http://tool.chinaz.com/tools/unicode.aspx
