### ISSUE TITLE
[BUG] IINA自定义播放器CPU占用高

### ISSUE THREAD

**Issue by sorosunrain** [xfangfang/Macast#51]
## Versions
MaOS: 11.5.2
Macast: v0.61
IINA: 1.2.0

图一：
使用IINA直接播放链接的CPU占用
<img width="494" alt="B" src="https://user-images.githubusercontent.com/10646353/132940464-dfcbb260-02b8-4f78-9d85-30b553fbcbe2.png">

图二：
使用投屏拉起IINA播放的CPU占用
<img width="577" alt="A" src="https://user-images.githubusercontent.com/10646353/132940476-f6360c32-cc85-469f-8388-06b4e299ac6c.png">

**Comment by xfangfang** [comment]
请问您是m1的mac吗？

这个就是popen开了一个进程启动iina，没理由会更高的，或者可以提供一个稳定的可供复现的链接，我在我本地是没有这个现象的（不过确实很有意思，使用mpv会比iina cpu占用高）

可以试试命令行调用iina-cli看看效果如何
也可以测试看看直接在python脚本里调用iina

```python
IINA_PATH = '/Applications/IINA.app/Contents/MacOS/iina-cli'
subprocess.Popen([IINA_PATH, '--keep-running', '--no-stdin', url])
```

**Comment by sorosunrain** [comment]
开启硬解后，占用百分之10几了~

**Comment by xfangfang** [comment]
可不可以展开详细讲讲呢，也为后来的朋友提个醒

**Comment by sorosunrain** [comment]
禁用改成自动了
<img width="740" alt="C" src="https://user-images.githubusercontent.com/10646353/132942484-6e07b24c-55f8-4bf0-a9eb-1b889bef3db5.png">
