### ISSUE TITLE
[BUG] Unhandled exception in script

### ISSUE THREAD

**Issue by MisakaSakura** [xfangfang/Macast#52]
## Versions

- System: Win11
- System version: 21H2(22000.184)
- Processor architecture: x64
- APP version: v0.61

## Bug recurrence

running the app on the win11

## Additional information
![image](https://user-images.githubusercontent.com/30547550/132941972-114a4478-aa37-4055-9a7a-1e022ed08d2c.png)

## Log

Starting Macast from terminal to get logs.

### Windows

download debug version of this application: [Download link](https://github.com/xfangfang/Macast/releases/latest)

### PasteBoard
```
# then paste your log here

```

**Comment by xfangfang** [comment]
Any more information?

**Comment by MisakaSakura** [comment]
我下载了debug版本但我不清楚你的日志位置在哪

**Comment by MisakaSakura** [comment]
> Any more information?

我下载了debug版本但我不清楚你的日志位置在哪

**Comment by xfangfang** [comment]
正常来说debug版会开启一个命令行窗口，如果看不到的话看起来是启动就失败了，是不是在配置文件中写入了中文呢？
我在本地的win11开启是直接用的，如果您有python环境的话，可以尝试 pip install macast==0.6.2 
然后命令行运行 macast-gui
这样应该就能看到log了，或者从源码直接运行也能查看到log，这个问题还是第一次出现

**Comment by xfangfang** [comment]
这也太神奇了！

不过说起来可以试试这个版本：https://github.com/xfangfang/Macast/actions/runs/1224102007

刚刚有人反馈了win11报错，他成功截下来log了，可以用试试行不行。
我把加群验证取消了，等你进群

**Comment by MisakaSakura** [comment]
@xfangfang 电脑可以正常申请，但是你可能没接到我的申请请求，我申请2次了

**Comment by xfangfang** [comment]
朋友你是不是做啥坏事了，我把群开成了没有验证随便进群，这可咋整

**Comment by xfangfang** [comment]
你可以直接加我qq，通过群应该可以看到的

**Comment by MisakaSakura** [comment]
@xfangfang 我啥也没干啊，连群都很少加了

**Comment by xfangfang** [comment]
更新一下，问题最后定位到电脑给手机开热点，这种情况下 linux未知，macos可以搜索到设备，windows无法搜索到设备。
原因是暂未找到有效手段检测到windows热点的网关开启的接口
