### ISSUE TITLE
[BUG] 和emby配合无法控制

### ISSUE THREAD

**Issue by ghostry** [xfangfang/Macast#54]
## Versions

- System: (Ubuntu)
- System version: (21.04)
- Processor architecture: (amd64)
- APP version: (0.6.1 deb包)

## Bug recurrence

使用安卓emby安卓客户端连接，emby服务端版本4.6.4，客户端版本3.1.63

## Additional information

点击播放后，不会自动出现控制菜单，需要手动，
手动进入控制后，音量，停止可用，进度控制无效，
暂停可用但是无法恢复，暂停后再点暂停按钮会断开，需要重连

## Log
error看到有两行，
[全部日志](https://gist.github.com/ghostry/c063a5eb30bdcef28acde04dfa0bd515)

```
ERROR:MPVRenderer:decode error 'reason'
ERROR:MPVRenderer:decode error ['{"event":"tracks-changed"}', '{"event":"end-file"}']
```

**Comment by xfangfang** [comment]
This build should fix the problem: https://github.com/xfangfang/Macast/actions/runs/1228257786

**Comment by ghostry** [comment]
> This build should fix the problem: https://github.com/xfangfang/Macast/actions/runs/1228257786

[完整日志](https://gist.github.com/ghostry/c063a5eb30bdcef28acde04dfa0bd515#gistcomment-3891234)

表现有改变，暂停恢复可用了。开始播放后会出现控制界面了。
进度调整有问题。直接点击无反应，有时候暂停再恢复，进度变了。有时候不会变。

**Comment by xfangfang** [comment]
我这边测试进度是没问题的，是不是进度跳转的慢了一些导致的呢，可以试着点一下等一等

**Comment by ghostry** [comment]
> 我这边测试进度是没问题的，是不是进度跳转的慢了一些导致的呢，可以试着点一下等一等

确实延迟，大概10秒左右，10秒左右会反应过来改变进度。
我尝试了换用 gmediarender 0.0.9 接收，进度调整延迟在1秒内。

**Comment by xfangfang** [comment]
感谢反馈，刚刚测试emby十秒与Macast同步一次数据，如果调整完进度紧接着再调整延迟就是近10s，目前不知道具体原因还在排查。

**Comment by xfangfang** [comment]
可以再试试这个：https://github.com/xfangfang/Macast/actions/runs/1232751459

问题出在emby的实现没有遵守DLNA协议，某些可选的播放器状态选项他并没有支持导致的，对比了一下小米电视的投屏接收端也没有支持那个功能，于是就移除了，现在应该可以了。

**Comment by ghostry** [comment]
> 可以再试试这个：https://github.com/xfangfang/Macast/actions/runs/1232751459
> 
> 问题出在emby的实现没有遵守DLNA协议，某些可选的播放器状态选项他并没有支持导致的，对比了一下小米电视的投屏接收端也没有支持那个功能，于是就移除了，现在应该可以了。

这个很顺畅了。 ｄ(▽￣*)

**Comment by xfangfang** [comment]
OK 感谢反馈，先把这个issue关闭了，有问题再交流
