### ISSUE TITLE
[BUG] Macast doesn't show up on the client after MacOS wakeup from sleeping

### ISSUE THREAD

**Issue by sorosunrain** [xfangfang/Macast#57]
## Versions

macOS: 11.5.2
macast: v0.61

## Bug recurrence

锁屏休眠，断网后，无法发现设备，必现。

**Comment by xfangfang** [comment]
您有没有发现手机开了飞行模式之后就打不了电话了，可能是一个原理吧

**Comment by sorosunrain** [comment]
描述有误，是再次打开，联网后。

**Comment by xfangfang** [comment]
这个问题我专门测试过按道理是不会发生的，可以下载最新测试版: https://github.com/xfangfang/Macast/actions/runs/1232751459
然后提交一下休眠断网前后的log，我看一看

**Comment by sorosunrain** [comment]
新版本v0.64没出现
