### ISSUE TITLE
希望可以将mpv的路径修改一下

### ISSUE THREAD

**Issue by AsimovGod** [xfangfang/Macast#58]
希望mpv可以先读取系统变量，我的电脑是装了mpv的。
建议不要把mpv放在用户文件夹下，太容易受到限制了，可以放在软件的目录下。

**Comment by xfangfang** [comment]
现在的预编译的版本macos和windows都是内置了mpv的，不会去调用用户已经安装的mpv避免因为mpv版本不同引入不稳定因素。


> 建议不要把mpv放在用户文件夹下，太容易受到限制了，可以放在软件的目录下。

这句话指的是什么？我有点没太看懂，内置的mpv是内置在打包好的应用内的，不会放置在用户的某个目录下。

**Comment by AsimovGod** [comment]
![图片](https://user-images.githubusercontent.com/75630897/133287600-6cdf14c0-9902-4b06-8ac8-187de404b9f5.png)
直接将mpv运行文件放入temp文件中，之前遇到过一次，各种系统保护，主要我用的是WD。
不过如果mpv不进行文件操作应该不会触发，但是我觉得将可执行二进制文件放在一起不太容易出问题。

**Comment by xfangfang** [comment]
这个tmp文件夹是应用运行时创建的临时工作目录，运行结束就不需要了（默写系统会自动删除，某些系统重启后会删除）
如果不使用这种只有一个文件的绿色打包方式，那么就需要修改的打包方式为安装包的形式，这样文件就放置在系统的软件目录了，这个之后我有时间会新增。

wd是什么缩写，西部世界？还是windows简称？
顺便一提，在github提issue最好还是按照issue模板来填写，格式更加标准也方便别的朋友查阅，描述内容尽量详细一些避免问来问去，耽误双方时间。
首页默认语言是英语，一般来说意味着这个仓库希望用户交流的主要语言为英语，因为也是有一些国外的用户也在使用的。
最后，如果是提出新的feature最好还是持着感谢的心情和言语，这样会让作者更容易接受您的建议。
放上一个我认为写的特别好的github使用说明：https://zhuanlan.zhihu.com/p/37599617

**Comment by AsimovGod** [comment]
WD是Windows Defender的简称，它的限制较为繁琐。不过已经国内使用WD的应该算少数了吧。  

关于表达，主要还是我英语实在太差，只能靠机翻。我只能保证我的表达的内容能被转述准确，至于感情语气，实在无法考虑，我也不知道机翻成什么样子。这次是看到有中文讨论所以用了中文，如果我的表达有不妥，请原谅,这种僵硬的表达短时间内大概无法改变了。我其实很喜欢和开发者们交流，但我使用这些平台的时间并不长，只能一点一点摸索的使用。Issue礼仪是有用的，我会去学习。

**Comment by xfangfang** [comment]
嗯嗯，感谢您的理解，我前面也并没有指责您的意思，大家都是从不了解到了解过来的，互相理解～

安装包的问题，我之后会新增支持安装的windows客户端满足大家的需求的，因为已经与原题无关了，先把这个issue关闭了。
