### ISSUE TITLE
[NEW FEATURE] Support automatic rotation of pictures

### ISSUE THREAD

**Issue by k2000ghm** [xfangfang/Macast#59]
## New feature
目前使用MIUI 12的手机投屏照片到电脑无法根据重力加速器数据自动旋转，希望可以加入支持

## Additional context
因手边没有其他设备，无法验证是否为MIUI自身的问题

**Comment by xfangfang** [comment]
As far as I know, DLNA protocol does not have this function.

[UPnP™ AVTransport:1 service](http://upnp.org/specs/av/UPnP-av-AVTransport-v1-Service.pdf)
[UPnP™ RenderingControl:1 service](http://upnp.org/specs/av/UPnP-av-RenderingControl-v1-Service.pdf)
