### ISSUE TITLE
未来会支持macos 10.14么(Will MacOS 10.14 be supported in the future)

### ISSUE THREAD

**Issue by lee29** [xfangfang/Macast#6]
RT

**Comment by xfangfang** [comment]
This project uses py2app to package the application which cannot be used on lower system versions than it compiled. And the releases is compiled through GitHub Action which is only supports MacOS10.15.

If you could find a CI system that support lower MacOS versions, feel free to submit code.

Or follow the  README's instructions to build your own application.
https://github.com/xfangfang/Macast#development-upder-macos

**Comment by xfangfang** [comment]
您好，这个版本理论上最低支持到10.12，但是我这边没有老版本系统的电脑没办法真机测试，如果您方便的话有空可以测试看看：https://github.com/xfangfang/Macast/actions/runs/1267354554

**Comment by lee29** [comment]
> 您好，这个版本理论上最低支持到10.12，但是我这边没有老版本系统的电脑没办法真机测试，如果您方便的话有空可以测试看看：https://github.com/xfangfang/Macast/actions/runs/1267354554

good job！！目前10.14工作正常

**Comment by xfangfang** [comment]
好的，那我先把这个issue关闭了，等下一个正式版本发布~
