### ISSUE TITLE
希望支持快捷键提示

### ISSUE THREAD

**Issue by fcwys** [xfangfang/Macast#61]
希望支持快捷键提示，如全屏、音量加减等，另外建议设置能在GUI界面操作，谢谢！

**Comment by xfangfang** [comment]
Relevant contents have been included in the: [Development plan](https://github.com/xfangfang/Macast/blob/main/README_ZH.md#开发计划)

请下次提issue的时候尽量使用issue模板和英语，格式更加标准，也能让更多人理解
