### ISSUE TITLE
[BUG] The device name cannot be modified to a non ASCII character

### ISSUE THREAD

**Issue by pianrendehaizhi** [xfangfang/Macast#64]
## Versions

- System: (eg:MacOS)
- System version: (eg:11.4)
- Processor architecture: (eg:X86)
- APP version: (eg: v0.2)

## Bug recurrence

投屏名称不支持中文名

**Comment by xfangfang** [comment]
目前需要中文转unicode填入，这个问题在linux上或者直接从源码运行就不存在，感觉是打包方式导致的，应该不太好解决

**Comment by xfangfang** [comment]
最新版本增加了设置的前端页面，可以直接设置中文了。

<img width="561" alt="image" src="https://user-images.githubusercontent.com/16631584/149403976-df26e8f7-9278-4ca9-a1e2-fb5ddf2efda0.png">
