### ISSUE TITLE
[BUG] B站直播无法投屏（Bilibili live can not be cast）

### ISSUE THREAD

**Issue by DandyChan** [xfangfang/Macast#67]
## Versions

- System: windows 10
- System version: 21H1
- Processor architecture: X64
- APP version: 0.6.4

## Bug recurrence

B站直播无法投屏。但测试腾讯体育直播，微博直播可以正常投屏。

Bilibili live can not be cast. But, TencentSports and weibo can run in normal.

**Comment by xfangfang** [comment]
b站直播投屏，可能最长需要等待超过30秒才可以搜索到，这个应该是b站的问题，只要第一次能投了，后面应该就不会了。
如果是ios用户，还要注意客户端的发现本地网络设备权限有没有正常开启

可以参考这个回答：https://github.com/xfangfang/Macast/issues/21#issuecomment-905193925
