### ISSUE TITLE
Windows客户端打开没有更换默认播放器

### ISSUE THREAD

**Issue by RyanGao-github** [xfangfang/Macast#68]
## Versions

- System: (eg:MacOS)
- System version: (eg:11.4)
- Processor architecture: (eg:X86)
- APP version: (eg: v0.2)

## Bug recurrence

(How to trigger this bug)

## Additional information

(More description of this bug)

## Log

Starting Macast from terminal to get logs.

### MacOS

run this in your terminal:
```
/Applications/Macast.app/Contents/MacOS/Macast
```

### Windows

download debug version of this application: [Download link](https://github.com/xfangfang/Macast/releases/latest)

### Linux

```
python Macast.py
```

### PasteBoard
```
# then paste your log here
在windows打开之后设置里面没有更换默认播放器这个选项
```

**Comment by xfangfang** [comment]
请先看完首页的使用说明

**Comment by RyanGao-github** [comment]
不好意思，我太菜了 😂
