### ISSUE TITLE
服务端发送SetAVTransportURI之后播放器不应该立即播放

### ISSUE THREAD

**Issue by zqbxx** [xfangfang/Macast#71]
DLNA服务端发送SetAVTransportURI指令后，播放器不应该立即开始播放，应该在发送Play指令后再开始播放，目前kodi和乐播投屏都是这样的
Play
```
<?xml version='1.0' encoding='utf-8'?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Body>
    <u:Play xmlns:u="urn:schemas-upnp-org:service:AVTransport:1">
      <InstanceID>0</InstanceID>
      <Speed>1</Speed>
    </u:Play>
  </s:Body>
</s:Envelope>
```

**Comment by xfangfang** [comment]
我认为你说的对，现在的播放器行为就好像是投放了媒体文件之后，人为手动点击了播放。

要不要改呢？我认为暂时还是不会改动，主要是我想不出来在什么情况下DLNA客户端会在投放媒体文件之后，先暂时等一会再开始播放，而且这种自动开启播放的做法也可以应对一些不按规则来的DLNA客户端，您认为呢？

**Comment by zqbxx** [comment]
> 
> 
> 我认为你说的对，现在的播放器行为就好像是投放了媒体文件之后，人为手动点击了播放。
> 
> 要不要改呢？我认为暂时还是不会改动，主要是我想不出来在什么情况下DLNA客户端会在投放媒体文件之后，先暂时等一会再开始播放，而且这种自动开启播放的做法也可以应对一些不按规则来的DLNA客户端，您认为呢？

以前碰到的问题，一直没提，具体情况记不清了，后来我重写代码避开了这个问题。
