### ISSUE TITLE
[Question] Documentation requirements

### ISSUE THREAD

**Issue by 6get-xiaofan** [xfangfang/Macast#78]
## Versions

- System version: Windows11 21996.1
- Processor architecture: X64
- APP version: v0.65

## Problem

Hello, is there a document corresponding to the shortcut keys of the built-in player? I need it very much, thank you!

**Comment by xfangfang** [comment]
Please refer to : https://github.com/xfangfang/Macast/wiki/FAQ#how-to-set-personal-configurations-to-mpv

**Comment by 6get-xiaofan** [comment]
Thanks!
