### ISSUE TITLE
[BUG] Ubuntu 21.10: "macast is running at the desktop panel" -but it is nowhere to be found!

### ISSUE THREAD

**Issue by heidiwenger** [xfangfang/Macast#85]
So Macast installed from the .deb and launched. But it is not to be found anywhere as running (to start casting from) in desktop. Maybe this same issue is present in Ubuntu 20.04 LTS also? Could it be a GNOME thing? How to get Macast visible by any chance?

## Versions

- System: (eg:Ubuntu 21.10)
- System version: (eg:11.4)
- Processor architecture: (eg:X86)
- APP version: (eg: v0.2)

## Bug recurrence

(How to trigger this bug)

## Additional information

(More description of this bug)

## Log

Starting Macast from terminal to get logs.

### MacOS

run this in your terminal:
```
/Applications/Macast.app/Contents/MacOS/Macast
```

### Windows

download debug version of this application: [Download link](https://github.com/xfangfang/Macast/releases/latest)

### Linux

```
python Macast.py
```

### PasteBoard
```
# then paste your log here

```

**Comment by xfangfang** [comment]
This is the reason: https://github.com/moses-palmer/pystray/issues/98#issuecomment-907620554

According to the project [wiki](https://github.com/xfangfang/Macast/wiki/Installation#tested-with-these-system), displaying icons on the status bar of Ubuntu requires additional dependencies to be installed.

```
sudo apt install libappindicator3-dev
```

**Comment by heidiwenger** [comment]
> Macast is a DLNA Renderer which only receiving media files from other DLNA client.

Ok, i see. Thanks! I'm trying to put together a guide for my friend to use Macast, so now i know these extra steps which have to be taken. 

That said, as additional step such as libappindicator3-dev install via command line is required, it can be very cumbersome for new and common computer users. Could there be a snap package at some point for Macast? That would include all needed dependencies etc? Also snap packages run in a sandbox, so theres that.

**Comment by xfangfang** [comment]
DEB can also install enough dependencies, but it can display icons normally without similar dependencies on other Linux systems. So I remove the deps.
It seems that Ubuntu has deliberately restricted the status bar icons, which should be decided by the users rather than the software developer to decide whether to install the dependencies?
I will upload it to snap later, but I don't have much time recently. It still need to wait.
