### ISSUE TITLE
[Bug]The App cannot quit by quit button

### ISSUE THREAD

**Issue by mikal** [xfangfang/Macast#89]
The app cannot quit by clicking "quit" in the menubar. Here are logs & running environment.

Model: MacbookPro A2141
OS: MacOS 11.5.2
APP：0.6.5
Logs:
`/Applications/Macast.app/Contents/MacOS/Macast
Macast Loading Default Language en_US
{'Additional_Interfaces': [], 'ApplicationPort': 1068, 'Blocked_Interfaces': [], 'CheckUpdate': 0, 'DLNA_FriendlyName': 'Macast(xxxxs-MBP.lan)', 'DLNA_Renderer': 'Default', 'MenubarIcon': 1, 'PlayerHW': 1, 'PlayerHW_Force': 1, 'PlayerSize_Auto': 2, 'StartAtLogin': 0, 'USN': 'a0fd2220-7261-4697-9813-622af674b466'}
Load renderer MPVRenderer done
using renderer: Default
2021-10-28 22:10:01.200 Macast[15272:761302] WARNING: the default quit button is disabled. To exit the application gracefully, another button should have a callback of quit_application or call it indirectly.`

Besides, I find Macast has traffic with 239.255.255.250. What are traffic for?
Thanks!

**Comment by mikal** [comment]
The application can be exited after being open for more than 10 mins.

`/Applications/Macast.app/Contents/MacOS/Macast
Macast Loading Default Language en_US
{'Additional_Interfaces': [], 'ApplicationPort': 54012, 'Blocked_Interfaces': [], 'CheckUpdate': 0, 'DLNA_FriendlyName': 'Macast(xxxx-MBP.lan)', 'DLNA_Renderer': 'Default', 'MenubarIcon': 1, 'PlayerHW': 1, 'PlayerHW_Force': 1, 'PlayerSize_Auto': 2, 'StartAtLogin': 0, 'USN': '4f1e5553-cbe0-4c7c-8dfd-78e32e5a15c0'}
Load renderer MPVRenderer done
using renderer: Default
2021-10-30 11:41:59.831 Macast[3937:489552] WARNING: the default quit button is disabled. To exit the application gracefully, another button should have a callback of quit_application or call it indirectly.
INFO:main:service_start
ERROR:SSDPServer:add membership 192.168.50.124
ERROR:SSDPServer:add membership 192.168.50.220
INFO:cherrypy.error:[30/Oct/2021:11:42:00] ENGINE Started monitor thread 'Autoreloader'.
INFO:cherrypy.error:[30/Oct/2021:11:42:00] ENGINE Started monitor thread 'SSDP_NOTIFY_THREAD'.
INFO:cherrypy.error:[30/Oct/2021:11:42:00] ENGINE Bus STARTED
INFO:main:Server current run on port: 54012
ERROR:MPVRenderer:mpv ipc socket start connect
INFO:MPVRenderer:{'event': 'property-change', 'id': 3, 'name': 'pause', 'data': False}
INFO:MPVRenderer:{'event': 'property-change', 'id': 1, 'name': 'volume', 'data': 50.0}
INFO:main:ssdp_update_ip
ERROR:SSDPServer:drop membership 192.168.50.124
ERROR:SSDPServer:drop membership 192.168.50.220
ERROR:SSDPServer:add membership 192.168.50.124
ERROR:SSDPServer:add membership 192.168.50.220
INFO:main:ssdp_update_ip
ERROR:SSDPServer:drop membership 192.168.50.124
ERROR:SSDPServer:drop membership 192.168.50.220
ERROR:SSDPServer:add membership 192.168.50.124
ERROR:SSDPServer:add membership 192.168.50.220
INFO:main:ssdp_update_ip
ERROR:SSDPServer:drop membership 192.168.50.124
ERROR:SSDPServer:drop membership 192.168.50.220
ERROR:SSDPServer:add membership 192.168.50.124
ERROR:SSDPServer:add membership 192.168.50.220
INFO:main:ssdp_update_ip
ERROR:SSDPServer:drop membership 192.168.50.124
ERROR:SSDPServer:drop membership 192.168.50.220
ERROR:SSDPServer:add membership 192.168.50.124
ERROR:SSDPServer:add membership 192.168.50.220
INFO:main:ssdp_update_ip
ERROR:SSDPServer:drop membership 192.168.50.124
ERROR:SSDPServer:drop membership 192.168.50.220
ERROR:SSDPServer:add membership 192.168.50.124
ERROR:SSDPServer:add membership 192.168.50.220
INFO:main:ssdp_update_ip
ERROR:SSDPServer:drop membership 192.168.50.124
ERROR:SSDPServer:drop membership 192.168.50.220
ERROR:SSDPServer:add membership 192.168.50.124
ERROR:SSDPServer:add membership 192.168.50.220
INFO:main:ssdp_update_ip
ERROR:SSDPServer:drop membership 192.168.50.124
ERROR:SSDPServer:drop membership 192.168.50.220
ERROR:SSDPServer:add membership 192.168.50.124
ERROR:SSDPServer:add membership 192.168.50.220
INFO:main:ssdp_update_ip
ERROR:SSDPServer:drop membership 192.168.50.124
ERROR:SSDPServer:drop membership 192.168.50.220
ERROR:SSDPServer:add membership 192.168.50.124
ERROR:SSDPServer:add membership 192.168.50.220
INFO:main:ssdp_update_ip
ERROR:SSDPServer:drop membership 192.168.50.124
ERROR:SSDPServer:drop membership 192.168.50.220
ERROR:SSDPServer:add membership 192.168.50.124
ERROR:SSDPServer:add membership 192.168.50.220
INFO:main:ssdp_update_ip
ERROR:SSDPServer:drop membership 192.168.50.124
ERROR:SSDPServer:drop membership 192.168.50.220
ERROR:SSDPServer:add membership 192.168.50.124
ERROR:SSDPServer:add membership 192.168.50.220
INFO:main:ssdp_update_ip
ERROR:SSDPServer:drop membership 192.168.50.124
ERROR:SSDPServer:drop membership 192.168.50.220
ERROR:SSDPServer:add membership 192.168.50.124
ERROR:SSDPServer:add membership 192.168.50.220
INFO:main:ssdp_update_ip
ERROR:SSDPServer:drop membership 192.168.50.124
ERROR:SSDPServer:drop membership 192.168.50.220
ERROR:SSDPServer:add membership 192.168.50.124
ERROR:SSDPServer:add membership 192.168.50.220
INFO:main:ssdp_update_ip
ERROR:SSDPServer:drop membership 192.168.50.124
ERROR:SSDPServer:drop membership 192.168.50.220
ERROR:SSDPServer:add membership 192.168.50.124
ERROR:SSDPServer:add membership 192.168.50.220
INFO:main:ssdp_update_ip
ERROR:SSDPServer:drop membership 192.168.50.124
ERROR:SSDPServer:drop membership 192.168.50.220
ERROR:SSDPServer:add membership 192.168.50.124
ERROR:SSDPServer:add membership 192.168.50.220
2021-10-30 11:49:17.262 Macast[3937:489552] <MenuItem: ['Quit' -> []; callback: <bound method MenuItem._rumpsCallback of <macast.gui.MenuItem object at 0x13a7cc910>>]>
INFO:cherrypy.error:[30/Oct/2021:11:49:17] ENGINE Bus STOPPING
INFO:cherrypy.error:[30/Oct/2021:11:49:18] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 54012)) shut down
INFO:cherrypy.error:[30/Oct/2021:11:49:18] ENGINE Stopped thread 'Autoreloader'.
INFO:cherrypy.error:[30/Oct/2021:11:49:18] ENGINE Stopped thread 'SSDP_NOTIFY_THREAD'.
INFO:MPVRenderer:stoping mpv and mpv ipc
ERROR:MPVRenderer:mpv ipc stopped
INFO:MPVRenderer:mpv stopped
INFO:main:service_stop
ERROR:SSDPServer:drop membership 192.168.50.124
ERROR:SSDPServer:drop membership 192.168.50.220
INFO:cherrypy.error:[30/Oct/2021:11:49:18] ENGINE Bus STOPPED
INFO:cherrypy.error:[30/Oct/2021:11:49:18] ENGINE Bus EXITING
INFO:cherrypy.error:[30/Oct/2021:11:49:18] ENGINE Bus EXITED
INFO:cherrypy.error:[30/Oct/2021:11:49:18] ENGINE Waiting for child threads to terminate...
INFO:main:Service stopped
2021-10-30 11:49:18.360 Macast[3937:489552] closing application`

**Comment by xfangfang** [comment]
this log shows:

1. Macast opened at 11:41:59
2. At 11:49:17, Quit button was clicked
3. And Macast closed at 11:49:18

It looks normal. Can you show me the log or screen recording when an error occurs?

**Comment by xfangfang** [comment]
Is there any update?
