### ISSUE TITLE
error with NetEase Cloud Music 

### ISSUE THREAD

**Issue by Tilie** [xfangfang/Macast#93]
## Versions

- System: Macos
- System version: 12.0.1 
- Processor architecture: X86
- APP version: v0.65

## Bug recurrence
open the DLNA features in NetEase Cloud Music and play the music with it.In the next few minutes,the app show the message "DLNA设备被占用" then the app drop the connection with macast,but music still play.
## Additional information
![image](https://user-images.githubusercontent.com/53890473/142396855-b96591c7-f278-4d7c-a12a-ae20867ca736.png)

## Log

Starting Macast from terminal to get logs.
[all_log.txt](https://github.com/xfangfang/Macast/files/7562011/all_log.txt)
when error message occur:
ERROR:SSDPServer:add membership 192.168.28.211
ERROR:SSDPServer:add membership 192.168.2.1
ERROR:SSDPServer:add membership 172.16.67.1
ERROR:SSDPServer:add membership 192.168.28.12
ERROR:SSDPServer:add membership 10.37.129.2
ERROR:SSDPServer:add membership 10.211.55.2

some information:
modem->my router->roommate's router
PPPOE in my router
192.168.28.* is my router 
192.168.2.1 maybe the modem?

**Comment by xfangfang** [comment]
Your network environment is too complex. Why did the computer get up to seven IP addresses?

When there are too many routers, the mobile phone may switch between routers, resulting in inability to access the computer. At this time, the application may show “DLNA设备被占用”. There is no problem testing in my network environment.

You can also try the beta version, which may help.
https://github.com/xfangfang/Macast/actions/runs/1431623419

**Comment by xfangfang** [comment]
因为没有后续更新，所以先关闭这个issue
