### ISSUE TITLE
Convert two assignment statements to augmented source code

### ISSUE THREAD

**Issue by elfring** [xfangfang/Macast#98]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

```diff
diff --git a/macast/renderer.py b/macast/renderer.py
index 7467781..eaeb6ee 100644
--- a/macast/renderer.py
+++ b/macast/renderer.py
@@ -88,7 +88,7 @@ class ObserveClient:
         conn = http.client.HTTPConnection(self.host, timeout=5)
         conn.request("NOTIFY", self.path, data, headers)
         conn.close()
-        self.seq = self.seq + 1
+        self.seq += 1
 
 
 class DataType(Enum):
@@ -276,7 +276,7 @@ class Renderer:
 
             except Exception as e:
                 logger.error("send event error: " + str(e))
-                client.error = client.error + 1
+                client.error += 1
                 if client.error > 10:
                     logger.debug("remove " + client.sid)
                     self.remove_subscribe(client.sid)
```

**Comment by xfangfang** [comment]
(Why does a new issue show comments 24 days ago?)

Because I often switch between multiple languages and sometimes avoid confusing some things, I use the style that is not recommended. Thank you very much for your advice. I will improve the code quality later
