### ISSUE TITLE
[BUG] Linux下法显示小图标

### ISSUE THREAD

**Issue by 2512821228** [xfangfang/Macast#99]
## Versions

- System: Linux(Ubuntu)
- System version: Ubuntu 21.10 gnome 40.4

## Bug recurrence

启动程序后，Linux没有显示小图标
![2021-12-10 19-32-30 的屏幕截图](https://user-images.githubusercontent.com/11994295/145568372-874afee6-610e-47a8-8279-44d62bdbec49.png)

**Comment by xfangfang** [comment]
![7A9781BB-69D6-42B1-814A-2CCA9B8E00EF](https://user-images.githubusercontent.com/16631584/145569102-0e15883d-ec3b-475d-942f-7a52f5fcec59.jpeg)

**Comment by 2512821228** [comment]
安装 libappindicator3-dev 后问题得到解决
The problem is solved after installing libappindicator3-dev.
